<?php
/**
 * @file
 * Code for the SBAC Digital Library Resources feature.
 */

include_once 'sbac_digital_library_resources.features.inc';

/**
 * Implements hook_theme().
 */
function sbac_digital_library_resources_theme($existing, $type, $theme, $path) {
  $items = array();
  // Digital Library Resources search templates.
  $items['views_view__digital_library_resources'] = array(
    'template' => 'views-view--digital-library-resources',
    'path' => drupal_get_path('module', 'sbac_digital_library_resources') . '/templates/views',
    'arguments' => array('view' => NULL),
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function sbac_digital_library_resources_form($form, &$form_state) {

  $form['sbac_digital_library_resources_text'] = array(
    '#type' => 'textfield',
  );
  $form['#submit'][] = 'sbac_digital_library_resources_form_submit';
  return system_settings_form($form);
}

/**
 * Form submit callback.
 */
function sbac_digital_library_resources_form_submit($form, &$form_state) {
  $form_state['redirect'] = array(
    'digital-library-resources',
    array(
      'query' => array(
        'keyword' => $form_state['values']['sbac_digital_library_resources_text'],
      ),
    ),  
  );
}
