<?php
/**
 * @file
 * Code for the SBAC Digital Library Resources feature.
 */

include_once 'sbac_digital_library_resources.features.inc';

function sbac_digital_library_resources_block_info() {
  // This example comes from node.module.
  $blocks['posted_w_distinction'] = array(
    'info' => t('Posted with Distinction'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sbac_digital_library_resources_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'posted_w_distinction':
      if(arg(1) == 'distinguished'){
        $block['content'] = l(t('Posted with Distinction Only'),'/digital-library-resources', array('attributes' => array('class' => array('distinguished'))));
      }
      else{
        $block['content'] = l('Posted with Distinction Only','/digital-library-resources/distinguished', array('attributes' => array('class' => array('all-content'))));
      }
      
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function sbac_digital_library_resources_theme($existing, $type, $theme, $path) {
  $items = array();
  // Digital Library Resources search templates.
  $items['views_view__digital_library_resources'] = array(
    'template' => 'views-view--digital-library-resources',
    'path' => drupal_get_path('module', 'sbac_digital_library_resources') . '/templates/views',
    'arguments' => array('view' => NULL),
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
      'sbac_digital_library_resources_view',
    ),
  );
  /**
  $items['views_view_fields__digital_library_resources'] = array(
    'template' => 'views-view-fields--digital-library-resources',
    'path' => drupal_get_path('module', 'sbac_digital_library_resources') . '/templates/views',
    'arguments' => array('view' => NULL),
    'original hook' => 'views_view_fields',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view_fields',
      'sbac_digital_library_resources_view_fields',
    ),
  );
   * 
   */
  
  return $items;
}

/**
 * Implements hook_form().
 */
function sbac_digital_library_resources_form($form, &$form_state) {
  $query = drupal_get_query_parameters();
  $form['sbac_digital_library_resources_text'] = array(
    '#type' => 'textfield',
    '#default_value' => ($query['keyword'] ? $query['keyword'] : '' ),
  );
  $form['submit'] = array(
     '#type' => 'submit',
     '#value' => t('Submit'),
  );
  $form['#submit'][] = 'sbac_digital_library_resources_form_submit';
  return $form;
}

/**
 * Form submit callback.
 */
function sbac_digital_library_resources_form_submit($form, &$form_state) {
  $query = array();
  $query = drupal_get_query_parameters();
  $query['keyword'] = $form_state['values']['sbac_digital_library_resources_text'];
  // Unset page number
  if($query['page']){
    unset($query['page']);
  }
  $form_state['redirect'] = array(
    'digital-library-resources',
    array(
      'query' => $query,
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function sbac_digital_library_resources_form_views_exposed_form_alter(&$form, &$form_state, $form_id){
  switch ($form['#id']) {
    case 'views-exposed-form-digital-library-resources-page':
      // Hide extra search fields
      $form['keyword']['#type'] = 'hidden';
      // Setting to false hides and defaults to sort order in the view
      $form['sort_order']['#access'] = FALSE;
      
      break;
  }
}

/**
 * Implements hook_apachesolr_query_alter().
 *
 * @param DrupalSolrQueryInterface $query
 *
 */

function sbac_digital_library_resources_apachesolr_query_alter(DrupalSolrQueryInterface $query) {  
  // Display only posted and posted with distinction
  $posting_options = array('0','1');
  $subquery = apachesolr_drupal_query('apachesolr');
  foreach ($posting_options as $posting_option) {
    $subsubquery = apachesolr_drupal_query('apachesolr');
    $subsubquery->addFilter('is_field_posting_options', $posting_option);
    $subquery->addFilterSubQuery($subsubquery, 'OR');
  }
  $query->addFilterSubQuery($subquery);
}