<?php

/**
 * @file.
 * Module to handle the Welcome Tutorial and related help topics.
 *
 * Provides:
 *  - Welcome tutorial output.
 *  - Exports the help topic alignment type.
 *  - Management related to the help topics nodes.
 */

include_once 'sbac_help.features.inc';

/**
 * Implements hook_update_projects_alter().
 *
 * @param $projects
 */
function sbac_help_update_projects_alter(&$projects) {
  unset($projects['sbac_help']);
}

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function sbac_help_theme($existing, $type, $theme, $path) {
  $themes = array();

  $themes['views_view__help_topics__block'] = array(
    'template' => 'templates/views-view--help-topics--block',
    'arguments' => array('view' => NULL),
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
      'sbac_help_preprocess_views_view__help_topics__block',
    ),
  );

  $themes['help_dropdown'] = array(
    'path' => drupal_get_path('module', 'sbac_help') . '/templates',
    'template' => 'help-drop-down',
  );

  $themes['welcome_tutorial_list'] = array(
    'variables' => array(
      'nid' => NULL,
      'title' => NULL,
      'summary' => NULL,
      'image' => NULL,
    ),
    'path' => drupal_get_path('module', 'sbac_help') . '/templates',
    'template' => 'welcome-tutorial-list',
  );

  $themes['welcome_tutorial_post'] = array(
    'variables' => array(
      'back_link' =>  NULL,
      'title'     => NULL,
      'image'     => NULL,
      'body'      => NULL,
    ),
    'path' => drupal_get_path('module', 'sbac_help') . '/templates',
    'template' => 'welcome-tutorial-post',
  );

  return $themes;
}

/*
 * Implements hook_menu().
 */
function sbac_help_menu() {
  $items['get-node-content'] = array(
    'title'         => 'Get Node Content',
    'page callback' => 'sbac_help_get_node_content',
    'access arguments'  => array('access content'),
    'type'          => MENU_CALLBACK,
  );

  $items['welcome-tutorial/remove/%'] = array(
    'title' => 'Welcome Tutorial Remove',
    'page callback' => 'sbac_help_remove',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('send approval emails'),
  );

  $items['welcome-tutorial/%ctools_js'] = array(
    'title'             => 'Welcome Tutorial',
    'page callback'     => 'sbac_help_welcome_callback',
    'page arguments'    => array(1),
    'access arguments'  => array('access content'),
    'type'              => MENU_CALLBACK,
  );

  $items['welcome-tutorial/%ctools_js/%node'] = array(
    'title'             => 'Welcome Tutorial',
    'page callback'     => 'sbac_help_welcome_callback',
    'page arguments'    => array(1, 2),
    'access arguments'  => array('access content'),
    'type'              => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Preprocessor for the help_topics__block view.
 *
 * @param $vars
 */
function sbac_help_preprocess_views_view__help_topics__block(&$vars){
	drupal_add_css(drupal_get_path('module','sbac_help') . '/css/help.css');
}

/**
 * Preprocessor to add modal js to pages.
 *
 * @param $vars
 */
function sbac_help_preprocess_help_dropdown(&$vars) {
  ctools_include('modal');
  drupal_add_js(drupal_get_path('module', 'sbac_help') . '/js/sbac_help.ctools.js');
  $js_settings = array('sbac-help-welcome-tutorial' => array('modalSize' => array('type' => 'fixed', 'width' => 900, 'height' => 750), 'modalTheme' => 'CtoolSbacWelcomeTutorial'));
  drupal_add_js($js_settings, 'setting');
  ctools_modal_add_js();
}

/**
 * Implements hook_preprocess_HOOK().
 * Prepares the template variables.
 * @param  [type] $vars [description]
 */
function sbac_help_preprocess_welcome_tutorial_list(&$vars) {
  // $vars['title'] = l($vars['title'], drupal_get_path_alias('node/' . $vars['nid']), array('attributes' => array('class' => 'use-ajax')));
  $vars['title'] = l($vars['title'], 'welcome-tutorial/nojs/' . $vars['nid'], array('attributes' => array('class' => 'use-ajax')));
  $vars['summary'] = truncate_utf8($vars['summary'], 140, TRUE);
  if (isset($vars['image'])) {
    $file = file_load($vars['image']);
    if ($file) {
      $file_url = file_create_url($file->uri);
      $vars['image'] = '<img src="' . $file_url . '" alt="' . $vars['img_alt'] . '">';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 * Prepares the template variables.
 * @param  [type] $vars [description]
 */
function sbac_help_preprocess_welcome_tutorial_post(&$vars) {
  $vars['back_link'] = l('Back to Topics', 'welcome-tutorial/nojs', array('attributes' => array('class' => 'use-ajax')));
  $vars['title'] = $vars['node']->title;
  $vars['body'] = $vars['node']->body['und'][0]['value'];

  if (!empty($vars['node']->field_help_icon)) {
    $file = file_load($vars['node']->field_help_icon['und'][0]['fid']);
    if ($file) {
      $file_url = file_create_url($file->uri);
      $vars['image'] = '<img src="' . $file_url . '" alt="' . $vars['node']->field_help_icon['und'][0]['fid'] . '">';
    }
  }
  unset($vars['node']);
}

/**
 * Unless disabled or first time user, trigger helper modal overlay
 */
function sbac_help_init() {
  drupal_add_js(drupal_get_path('module','sbac_help') . '/js/help.js');

  global $user;
  // added check to make sure not on path change-password
  if (isset($_COOKIE['Drupal_visitor_sbac_just_logged_in']) && arg(0) != 'change-password') {
    if (!isset($user->data['disable_help']) || (isset($user->data['disable_help']) && $user->data['disable_help'] == 0)) {
      drupal_add_js("window.onload = function () { document.getElementById('sbac-help-welcome-tutorial').click(); };", array('type' => 'inline'));
    }
    // remove cookie moved to sbac_help_disable_help function to ensure its removed only when welcome modal is displayed
  }
}

/*
 * Form to enable/disable helper modal
 */
function sbac_help_disable_help() {
  global $user;
  $form = array();

  $form['disable_help'] = array (
    '#type'           => 'checkbox',
    '#title'          => t('Do not show this screen after next Log in') . '<br /><i>' . t('View this screen again by selecting Welcome Tutorial from Help on top menu') . '</i>',
  );

  $form['submit'] = array (
    '#type'           => 'submit',
    '#value'          => 'Close Welcome Tutorial',
  );

  if (!isset($user->data['disable_help'])) {
    $form['disable_help']['#default_value'] = 0;
  }
  else {
    $form['disable_help']['#default_value'] = $user->data['disable_help'];
  }
  // remove cookie only when welcome modal is displayed
  user_cookie_delete('sbac_just_logged_in');
  return $form;
}

/**
 * Submit handler for form submit.
 *
 * @param $form
 * @param $form_state
 */
function sbac_help_disable_help_submit($form, &$form_state) {
  global $user;

  user_save($user, array(
    'data' => array(
      'disable_help' => (int) $form_state['values']['disable_help'],
    )
  ));

  // $url = $form_state['redirect'] = 'digital-library-resources';
  // drupal_goto($url);
}

/**
 * Implements hook_preprocess_page().
 *
 * @param $variables
 */
function sbac_help_preprocess_page(&$variables) {
  global $user;
  $variables['help_dropdown'] = NULL;
  if ($user->uid) {
    $variables['help_dropdown'] = theme('help_dropdown');
  }
}

/**
 * Function callback for get-node-content
 *
 * @param $nid
 */
function sbac_help_get_node_content() {
  $nid = $_GET['nid'];
  if ($nid) {
    $node = node_load($nid, $vid = NULL, $reset = FALSE);
    if ($node) {
      $node_view = node_view($node, $view_mode = 'full', $langcode = NULL);
      $data = array(
        'results' => array(
          'body' => drupal_render($node_view['body']),
          'title' => $node->title
        )
      );
      return drupal_json_output($data);
    }
  }
  exit();
}

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function sbac_help_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'help_page_node_form') {
    unset($form['field_help_permissions']);
    $form['actions']['submit']['#submit'][] = 'sbac_help_remove_previous_resource_tutorial';
  }
}

/**
 * Remove the previously set resource tutorial help page
 *
 * @param $form
 * @param $form_state
 */
function sbac_help_remove_previous_resource_tutorial(&$form, &$form_state) {
  foreach ($form['field_help_page_topic']['und']['#options'] as $key => $value) {
    if ($value == 'Resource Tutorial') {
      $val = $key;
    }
  }
  // Check if Resource Tutorial checkbox is checked
  $nid = $form_state['values']['nid'];
  if (isset($val) && $form_state['input']['field_help_page_topic']['und'][$val]) {
    db_query('DELETE FROM {field_data_field_help_page_topic} WHERE field_help_page_topic_tid = :val AND entity_id <> :nid', array(':val' => $val, ':nid' => $nid));
    db_query('DELETE FROM {field_revision_field_help_page_topic} WHERE field_help_page_topic_tid = :val AND entity_id <> :nid', array(':val' => $val, ':nid' => $nid));
  }
}

/*
 * Implements hook_permission().
 *
 * remove welcome topics from list
 */
function sbac_help_permission() {
  return array(
    'send approval emails' => array(
      'title' => t('remove from list'),
    ),
  );
}

function sbac_help_remove($nid) {
  $node = node_load($nid);
  $node->field_help_page_topic = array();

  node_save($node);
  drupal_goto(drupal_get_origin() . '#topics-tab2');
}

function drupal_get_origin() {
  /* @var $_SERVER HTTP_REFERER works on our servers. */
  $path = $_SERVER['HTTP_REFERER'];
  if (isset($_GET['destination'])) {
    $path = $_GET['destination'];
  }
  return $path;
}

/*
 * Implements hook_form_alter().
 *
 * change "save" to "save order"
 */
function sbac_help_form_views_form_help_topics_page_2_alter(&$form, &$form_state, $form_id) {
  $form['actions']['submit']['#value'] = 'Save Order';
  $form['actions']['reset'] = array(
    '#type'   =>  'submit',
    '#value'  =>  'Reset to Alphabetical',
    '#submit' =>  array('sbac_help_delete_draggableviews_weights'),
  );
}

function sbac_help_form_views_form_help_topics_page_4_alter(&$form, &$form_state, $form_id) {
  $form['actions']['submit']['#value'] = 'Save Order';
  $form['actions']['submit']['#submit'][] = 'sbac_help_stay_on_welcome_tutorial_tab';
}

function sbac_help_stay_on_welcome_tutorial_tab(&$form, &$form_state) {
  drupal_custom_goto('/admin/help-topics#topics-tab2');
}

/**
 * Delete previous draggableviews weights on sort help topics screen
 *
 * @param $form
 * @param $form_state
 */
function sbac_help_delete_draggableviews_weights(&$form, &$form_state) {
  db_delete('draggableviews_structure')
    ->condition('view_name', 'help_topics')
    ->condition('view_display', 'page_2')
    ->execute();
}

/**
 * Implements hook_query_alter().
 * Only displays help topics associated to user roles.
 * @param  QueryAlterableInterface $query A Query object describing the composite parts of a SQL query.
 */
function sbac_help_query_alter(&$query) {
  if ($query->hasTag('views_help_topics')) {
    global $user;
    $roles = $user->roles;

    $can_view_all = array(
      'DLRB member',
      'digital library administrator',
      'system administrator',
    );

    // Do not alter view if user is allowed to view all or site admin.
    if ($user->uid == 1 || array_intersect($roles, $can_view_all)) {
      return;
    }

    $user_roles = array();

    // Add 'All User Roles'
    $all_roles = taxonomy_get_term_by_name('All User Roles', 'sbac_user_roles');
    $all_roles = array_pop($all_roles);
    if ($all_roles) {
      $user_roles[] = $all_roles->tid;
    }

    foreach($roles as $rid => $role) {
      $term = taxonomy_get_term_by_name($role, 'sbac_user_roles');
      $term = array_pop($term);
      $user_roles[] = $term->tid;
    }

    $query->innerJoin('field_data_field_help_user_roles',
                      'sur',
                      'node.nid = sur.entity_id');
    $query->condition('sur.field_help_user_roles_tid', $user_roles, 'IN');
    $query->groupBy('node.nid');
  }
}

/**
 * Implements hook_post_features_revert().
 * @param  String   $component String name of the component that has just been reverted.
 */
function sbac_help_post_features_revert($component) {
  if ($component == 'field_instance') {
    $instance_info = field_info_instance('node', 'field_help_user_roles', 'help_page');
    if (isset($instance_info['default_value'][0]['tid'])) {
      $term = taxonomy_get_term_by_name('All User Roles', 'sbac_user_roles');
      $term = array_pop($term);
      $instance_info['default_value'][0]['tid'] = $term->tid;
      field_update_instance($instance_info);
    }
  }
}

/**
 * Callback for Welcome Tutorial.
 * @param  boolean $js   ctools_js enabled
 * @param  stdObj  $node Node object to be rendered.
 */
function sbac_help_welcome_callback($js = FALSE, $node = FALSE) {
  if ($js) {
    ctools_include('ajax');
    ctools_include('modal');
    ctools_add_js('ajax-responder');
    ctools_modal_add_js();

    $title      = 'Welcome to the Smarter Balanced Digital Library';
    $tutorials  = sbac_help_welcome_tutorial_topics();

    $form_state = array(
      'title'     => t($title),
      'ajax'      => TRUE,
      'packages'  => array(
        'tutorials' => $tutorials,
        'node'      => $node,
      ),
    );

    if (!$node) {
      $output = ctools_modal_form_wrapper('sbac_help_welcome_tutorial_list_form', $form_state);
    }
    else {
      $output = ctools_modal_form_wrapper('sbac_help_welcome_tutorial_list_form', $form_state);
    }

    if (!empty($form_state['executed'])) {
      if ($form_state['triggering_element']['#value'] == 'Close Tutorial') {
        $output = array();
        $output[] = ctools_modal_command_dismiss();
      }
    }

    print ajax_render($output);
    exit();
  }
  else {
    return;
  }
}

/**
 * Implements hook_form().
 * Generates form for SBAC Welcome tutorial.
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function sbac_help_welcome_tutorial_list_form($form, &$form_state) {
  $form = array();
  global $user;

  $form['container_prefix'] = array(
    '#prefix' => '<div class="welcome-modal-container">',
  );

  $form['tutorial_header'] = array(
    '#markup' => '<div class="sbac-tutorial-header-cont">',
  );

  if (!($form_state['packages']['node'])) {
    $form['tutorial_topics'] = array(
      '#markup' => '<h2>Tutorial Topics</h2>',
    );

    $admin_roles = array(
      'administrator',
      'digital library administrator',
      'system administrator',
    );
    if (array_intersect($user->roles, $admin_roles)) {
      $form['edit_topics'] = array(
        '#prefix' => '<div class="welcome-tutorial-edit-topics">',
        '#markup' => l('Edit topics', 'admin/help-topics'),
        '#suffix' => '</div>',
      );
    }

    $form['tutorial_header_suffix'] = array(
      '#markup' => '</div>',
    );

    foreach ($form_state['packages']['tutorials'] AS $idx => $tutorial) {
      $form['tutorial-' . $tutorial['nid']] = array(
        '#markup' => theme('welcome_tutorial_list',
          array(
            'nid'     => $tutorial['nid'],
            'title'   => $tutorial['title'],
            'summary' => strip_tags($tutorial['body']),
            'image'   => $tutorial['img_fid'],
            'img_alt' => $tutorial['img_alt'],
          )
        ),
      );
    }
  }
  else {
    $form['tutorial-post'] = array(
      '#markup' => theme(
        'welcome_tutorial_post',
        array(
          'node' => $form_state['packages']['node'],
        )
      ),
    );
  }

  $form['container_suffix'] = array(
    '#suffix' => '</div>',
  );

  $form['button_prefix'] = array(
    '#prefix' => '<div class="welcome-modal-buttons">',
  );

  $form['disable_tut'] = array(
    '#type' => 'checkbox',
    '#title' => 'Do not show this tutorial again.',
    '#description' => "You can always find it under 'Help' in the top menu.",
    '#default_value' => $user->data['disable_help'],
    '#attributes' => array(
      'class' => array(
        'welcome-tut-do-not-show'
      ),
    ),
  );

  $form['close_tutorial'] = array(
    '#type' => 'submit',
    '#value' => 'Close Tutorial',
    '#attributes' => array(
      'class' => array(
        'button',
        'gray',
      ),
    ),
  );

  $form['button_suffix'] = array(
    '#suffix' => '</div>',
  );

  return $form;
}

function sbac_help_welcome_tutorial_list_form_submit($form, &$form_state) {
  global $user;
  user_save(
    $user,
    array(
      'data' => array(
        'disable_help' => (int) $form_state['values']['disable_tut'],
      )
    )
  );
}

/**
 * Returns a list of Node Entities that the currently logged in user can view.
 * @return array of stdClass representing nodes.
 */
function sbac_help_welcome_tutorial_topics() {
  $welcome_term = array_pop(taxonomy_get_term_by_name('Welcome tutorial', 'help_page_topic'));
  $roles = array();
  $topics = array();

  global $user;
  foreach ($user->roles AS $idx => $role) {
    $roles[] = array_pop(taxonomy_get_term_by_name($role, 'sbac_user_roles'))->tid;
  }
  $roles[] = array_pop(taxonomy_get_term_by_name('All User Roles', 'sbac_user_roles'))->tid;

  $query = 'SELECT    n.nid AS nid,
                      n.title AS title,
                      body.body_value AS body,
                      icon.field_help_icon_fid AS img_fid,
                      icon.field_help_icon_alt AS img_alt
            FROM      {node} n
            LEFT JOIN {field_data_body} body
              ON      n.nid = body.entity_id
            LEFT JOIN {field_data_field_help_page_topic} topic
              ON      n.nid = topic.entity_id
            LEFT JOIN {field_data_field_help_user_roles} roles
              ON      n.nid = roles.entity_id
            LEFT JOIN {field_data_field_help_icon} icon
              ON      n.nid = icon.entity_id
            LEFT JOIN {draggableviews_structure} weight
              ON      n.nid = weight.entity_id
                AND   weight.view_name = :view_name
                AND   weight.view_display = :view_page
            WHERE     n.type = :type
              AND     topic.field_help_page_topic_tid = :tid
              AND     roles.field_help_user_roles_tid IN (:roles)
            ORDER BY COALESCE(weight.weight, 10000) ASC
           ';

  $results = db_query($query, array(
    ':view_name' => 'help_topics',
    ':view_page' => 'page_4',
    ':type' => 'help_page',
    ':tid' => $welcome_term->tid,
    ':roles' => $roles,
    )
  );

  while ($result = $results->fetchAssoc()) {
    $topics[] = $result;
  }

  return $topics;
}
