# vim: sw=2:ts=2:et
Feature: SBAC Resource Taxonomy Educational Use
	As an admin user I should be able to view the Educational Use taxonomy with correct terms

  Scenario: Log in and go to "Educational Use taxonomy page" as a known admin user
    Given I am on the homepage
    When I fill in the following:
      | Email Address | admin |
      | Password | password |
    And press "Log into the Digital Library"
    Then I should be on the homepage

    When I am on "admin/structure/taxonomy/educational_use"
    Then I should see "Activity"
    And I should see "Analogies"
    And I should see "Assessment"
	And I should see "Auditory"
	And I should see "Brainstorming"
	And I should see "Classifying"
	And I should see "Comparing"
	And I should see "Cooperative Learning"
	And I should see "Creative Response"
	And I should see "Demonstration"
	And I should see "Differentiation"
	And I should see "Discovery Learning"
    And I should see "Discussion/Debate"
    And I should see "Drill & Practice"
    And I should see "Experiential Learning"
    And I should see "Field Trip"
	And I should see "Game"
    And I should see "Generating Hypotheses"
    And I should see "Guided Questions"
    And I should see "Hands-On"
    And I should see "Homework"
	And I should see "ID Similarities & Differences"
    And I should see "Inquiry"
    And I should see "Interactive"
    And I should see "Interview/Survey"
    And I should see "Interviews"
	And I should see "Introduction"
    And I should see "Journaling"
    And I should see "Kinesthetic"
    And I should see "Laboratory"
    And I should see "Lecture"
    And I should see "Manipulative"
	And I should see "Metaphors"
    And I should see "Model & Simulation"
    And I should see "Musical"
    And I should see "Nonlinguistic"
    And I should see "Note Taking"
    And I should see "Peer Coaching"
	And I should see "Peer Response"
    And I should see "Play"
    And I should see "Presentation"
    And I should see "Problem Solving"
    And I should see "Problem-Based"
    And I should see "Project"
    And I should see "Questioning"
    And I should see "Reading"
    And I should see "Reciprocal Teaching"
    And I should see "Reflection"
    And I should see "Reinforcement"
    And I should see "Research"
    And I should see "Review"
    And I should see "Robotics"
    And I should see "Role Playing"
    And I should see "Service Learning"
    And I should see "Simulations"
    And I should see "Speaker"
    And I should see "Summarizing"
    And I should see "Technology"
    And I should see "Testing Hypotheses"
    And I should see "Thematic Instruction"
    And I should see "Visual/Spatial"
    And I should see "Word Association"
    And I should see "Writing"

#As #1 user, view Educational Use taxonomy, see the correct terms