# vim: sw=2:ts=2:et
Feature: SBAC Resource Taxonomy States
	As an admin user I should be able to view the States taxonomy with correct terms

  Scenario: Log in and go to "States taxonomy page" as a known admin user
    Given I am on the homepage
    When I fill in the following:
      | Email Address | admin |
      | Password | password |
    And press "Log into the Digital Library"
    Then I should be on the homepage

    When I am on "admin/structure/taxonomy/states"
    Then I should see "Alabama"
    And I should see "Alaska"
    And I should see "American Samoa"
	And I should see "Arizona"
	And I should see "Arkansas"
	And I should see "Armed Forces Africa, Canada, Europe And Middle East"
	And I should see "Armed Forces Americas"
	And I should see "Armed Forces Pacific"
	And I should see "California"
	And I should see "Colorado"
	And I should see "Connecticut"
	And I should see "Consortium"
    And I should see "Delaware"
    And I should see "District Of Columbia"
    And I should see "Federated States Of Micronesia"
    And I should see "Florida"
    And I should see "Georgia"
    And I should see "Guam"
    And I should see "Hawaii"
    And I should see "Idaho"
    And I should see "Illinois"
	And I should see "Indiana"
    And I should see "Iowa"
    And I should see "Kansas"
    And I should see "Kentucky"
    And I should see "Louisiana"
    And I should see "Maine"
    And I should see "Marshall Islands"
    And I should see "Maryland"
    And I should see "Massachusetts"
    And I should see "Michigan"
	And I should see "Minnesota"
    And I should see "Mississippi"
    And I should see "Missouri"
    And I should see "MO"
    And I should see "Montana"
    And I should see "Nebraska"
    And I should see "Nevada"
    And I should see "New Hampshire"
    And I should see "New Jersey"
    And I should see "New Mexico"
	And I should see "New York"
    And I should see "North Carolina"
    And I should see "North Dakota"
    And I should see "Northern Mariana Islands"
    And I should see "Ohio"
    And I should see "Oklahoma"
    And I should see "Oregon"
    And I should see "Other"
    And I should see "Palau"
    And I should see "Pennsylvania"
    And I should see "Puerto Rico"
    And I should see "Rhode Island"
    And I should see "Smarter Balanced"
    And I should see "South Carolina"
    And I should see "South Dakota"
    And I should see "Tennessee"
    And I should see "Texas"
    And I should see "Utah"
    And I should see "Vermont"
    And I should see "Virgin Islands"
    And I should see "Virginia"
    And I should see "Washington"
    And I should see "West Virginia"
    And I should see "Wisconsin"
    And I should see "Wyoming"

#As #1 user, view States taxonomy, see the correct terms