<?php

/**
 * @file.
 *
 *
 * Provides:
 *  - Handles add / delete for materials (doc, pdf, excel, ppt etc)
 *  - Creates UI for add / delete
 *  - Hanldes upload / deletion of HTML5 modules
 *  - Handles vimeo, youtube, schooltube, teachertube and slideshare adding / deleting
 *  - Exports custom entity type for media
 */

include_once 'sbac_workbench.features.inc';

/**
 * Implements hook_update_projects_alter().
 *
 * @param $projects
 */
function sbac_workbench_update_projects_alter(&$projects) {
  unset($projects['sbac_workbench']);
}