<?php
/**
 * @file
 * Code for the SBAC resource feature.
 */

include_once 'sbac_resource.features.inc';
include_once 'sbac_resource.forms.inc';
include_once 'sbac_resource.theme.inc';

// Count.
define('SBAC_RESOURCE_MY_RESOURCES_COUNT', 'sbac-my-resources-count');
define('SBAC_RESOURCE_DIGITAL_LIBRARY_RESOURCES_COUNT', 'sbac-digital-library-resources-count');
define('SBAC_RESOURCE_RESOURCE_REVIEW', 'sbac-resoruce-review-count');

// View Mode.
define('SBAC_RESOURCE_DIGITAL_LIBRARY_RESOURCES_VIEW_MODE', 'sbac-dl-view-mode');
define('SBAC_RESOURCE_MY_RESOURCES_VIEW_MODE', 'sbac-mr-view-mode');
define('SBAC_RESOURCE_RESOURCE_REVIEW_VIEW_MODE', 'sbac-rr-view-mode');

/**
 * Implements hook_update_projects_alter().
 *
 * @param $projects
 */
function sbac_resource_update_projects_alter(&$projects) {
  unset($projects['sbac_resource']);
}

/**
 * Implements hook_menu().
 *
 * @return mixed
 */
function sbac_resource_menu() {
  $items = array();

  $items['sbac_resource/%ctools_js/add-alignment'] = array(
    'page callback' => 'sbac_resource_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'sbac_resource.forms.inc',
  );

  $items['sbac_resource/%ctools_js/filter-by-alignment'] = array(
    'page callback' => 'sbac_resource_filter_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'sbac_resource.forms.inc',
  );

  $items['sbac_resource/%ctools_js/submit-resource'] = array(
    'page callback' => 'sbac_resource_submit_resource_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'sbac_resource.forms.inc',
  );

  $items['sbac_resource/%ctools_js/delete-resource'] = array(
    'page callback' => 'sbac_resource_delete_resource_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'sbac_resource.forms.inc',
  );

  $items['sbac_resource/%ctools_js/save-all-changes'] = array(
    'page callback' => 'sbac_resource_save_all_changes_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'sbac_resource.forms.inc',
  );

  $items['digital-library-resources'] = array(
    'title' => 'Digital Library Resources',
    'page callback' => 'sbac_resource_digital_library_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
    'file' => 'sbac_resource.menu_callbacks.inc',
  );

  $items['my-resources'] = array(
    'title' => 'My Resources',
    'page callback' => 'sbac_resource_my_resources_page',
    'access callback' => 'sbac_resource_my_resources_access_callback',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -48,
    'file' => 'sbac_resource.menu_callbacks.inc',
  );

  $items['resource-review'] = array(
    'title' => 'Resource Review',
    'page callback' => 'sbac_resource_resource_review_page',
    'access callback' => 'sbac_resource_resource_review_access_callback',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
    'file' => 'sbac_resource.menu_callbacks.inc',
  );

  $items['admin/structure/types/manage/%node_type/messages'] = array(
    'title' => 'Messages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sbac_resource_form_messages'),
    'access arguments' => array(4),
    'access callback' => array('sbac_resource_form_messages_access'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'file' => 'sbac_resource.admin.inc',
  );

  return $items;
}

/**
 * Outputs the profile fields.
 *
 * @param $node
 */
function sbac_resource_profile_fields(&$node) {
  $resource_node = $node['node'];
  // Subjects and Domains
  if (isset($resource_node->field_subject['und']['0'])) {
    $resource_node->resource_profile_left['subjects']['title'] = 'Subjects and Domains';
    $resource_node->resource_profile_left['subjects']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_subject);
  }

  // Common Core State Standards
  if (isset($resource_node->field_alignment_term['und']['0'])) {
    $resource_node->resource_profile_left['ccss']['title'] = 'Common Core State Standards';
    $resource_node->resource_profile_left['ccss']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_alignment_term, TRUE);
  }

  // Grades
  if (isset($resource_node->field_grades['und']['0'])) {
    $resource_node->resource_profile_left['grades']['title'] = 'Grades';
    $resource_node->resource_profile_left['grades']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_grades);
  }

  // Intended End Use
  if (isset($resource_node->field_intended_end_user['und']['0'])) {
    $resource_node->resource_profile_left['end_use']['title'] = 'Intended End Users';
    $resource_node->resource_profile_left['end_use']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_intended_end_user);
  }

  // Intended Student Populations
  if (isset($resource_node->field_intended_student['und']['0'])) {
    $resource_node->resource_profile_left['student_pop']['title'] = 'Intended Student Populations';
    $resource_node->resource_profile_left['student_pop']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_intended_student);
  }

  // Media Types
  if (isset($resource_node->field_digital_media_type['und']['0'])) {
    $resource_node->resource_profile_left['media']['title'] = 'Media Types';
    $resource_node->resource_profile_left['media']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_digital_media_type);
  }

  // Educational Use
  if (isset($resource_node->field_educational_use['und']['0'])) {
    $resource_node->resource_profile_left['educational']['title'] = 'Educational Use';
    $resource_node->resource_profile_left['educational']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_educational_use);
  }

  // Technologies for use in classroom
  if (isset($resource_node->field_classroom_technologies['und']['0'])) {
    $resource_node->resource_profile_left['classroom']['title'] = 'Technologies Required for use in Classroom';
    $resource_node->resource_profile_left['classroom']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_classroom_technologies);
  }

  // Geographics Settings
  if (isset($resource_node->field_geographical_settings['und']['0'])) {
    $resource_node->resource_profile_left['geo']['title'] = 'Geographics Settings';
    $resource_node->resource_profile_left['geo']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_geographical_settings);
  }

  // Smarter Balanced Keywords
  if (isset($resource_node->field_smarter_balanced_keyword['und']['0'])) {
    $resource_node->resource_profile_left['smarter']['title'] = 'Smarter Balanced Keywords';
    $resource_node->resource_profile_left['smarter']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_smarter_balanced_keyword);
  }

  // License for primary material
  if (isset($resource_node->field_license['und']['0'])) {
    $resource_node->resource_profile_left['primary']['title'] = 'License For Primary Material';
    $resource_node->resource_profile_left['primary']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_license);
  }

  // License for a secondary material
  if (isset($resource_node->field_license_secondary['und']['0'])) {
    $resource_node->resource_profile_left['secondary']['title'] = 'Licenses For Secondary Material';
    $resource_node->resource_profile_left['secondary']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_license_secondary);
  }

  // Focus
  if (isset($resource_node->field_attributes['und']['0'])) {
    $resource_node->resource_profile_right['attributes']['title'] = 'Attributes of the Formative Assessment Process';
    $resource_node->resource_profile_right['attributes']['content'] = sbac_resource_get_taxonomy_terms($resource_node->field_attributes);
  }

  $node['node'] = $resource_node;
}

/**
 * @param $field
 * @return string
 */
function sbac_resource_get_taxonomy_terms($field, $ccss = FALSE) {
  $terms = array();
  foreach ($field['und'] as $key => $term) {
    if ($ccss) {
      $terms[] = $term['taxonomy_term']->field_alignment_shortname['und'][0]['value'];
    }
    else {
      $terms[] = $term['taxonomy_term']->name;
    }
  }

  $list = theme('item_list', array('items' => $terms, 'title' => '', 'type' => 'ul', 'attributes' => array('class' => 'field-content')));
  return $list;
}

/**
 * Returns the related resources for a given nid.
 *
 * @param $nid
 * @return string
 */
function sbac_resource_related_resources($nid) {
  $output = '';

  if ($nid) {
    $resource_node = node_load($nid);
    if ($resource_node) {
      $output = theme('sbac_resource_related_resources_header');
      $related_resources = sbac_resource_get_related_resources($resource_node);
      if ($related_resources) {
        if (count($related_resources) > 3) {
          drupal_add_js(drupal_get_path('module', 'sbac_resource') . '/js/sbac_resource.related_resources.js');
        }
        $output .= sbac_share_create_resource_card($related_resources);
      }
      else {
        $output .= theme('sbac_resource_no_related_resources');
      }
    }
  }

  return $output;
}

/**
 * Takes the baseline resource node and compares the subject,
 * grade and attributes to find related resources.
 *
 * @param $node
 * @return array
 */
function sbac_resource_get_related_resources($baseline_node) {
  // create baseline, then create query, then weight/sort, then return array list.
  $related_resources = array();
  $baseline_subjects = array();
  if (isset($baseline_node->field_subject['und'][0]['tid'])) {
    foreach ($baseline_node->field_subject['und'] as $key => $term) {
      $baseline_subjects[] = $term['tid'];
    }
  }
  $baseline_grades = array();
  if (isset($baseline_node->field_grades['und'][0]['tid'])) {
    foreach ($baseline_node->field_grades['und'] as $key => $term) {
      $baseline_grades[] = $term['tid'];
    }
  }
  $baseline_attributes = array();
  if (isset($baseline_node->field_attributes['und'][0]['tid'])) {
    foreach ($baseline_node->field_attributes['und'] as $key => $term) {
      $baseline_attributes[] = $term['tid'];
    }
  }

  /**
   *  Baseline Resource:  Subjects A, B, C; Grades 1, 2; Formative Assessment X, Y
   *
   *  To determine the nine (9) related resources, the system undergoes a layered comparison:
   *
   *  Subjects A OR Subjects B OR Subjects C AND
   *  Grades 1 OR Grades 2 AND
   *  Formative Assessment X OR Formative Assessment Y
   *
   *  If a resource does not match any of the subject tags (A, B, C) it is not subjected to the other filters.
  */
  // Compare baseline subjects against all other resource nodes.
  if ($baseline_subjects) {
    $baseline_subjects_string = implode(',', $baseline_subjects);
    // Check against baseline subjects.
    $query = "
            SELECT
              n.nid,
              s.field_subject_tid AS subject
            FROM {node} n
            JOIN {workbench_moderation_node_history} w ON n.nid = w.nid AND n.vid = w.vid
            JOIN {field_data_field_subject} s ON n.nid = s.entity_id AND n.vid = s.revision_id
            WHERE n.type = 'resource'
            AND w.state = 'published'
            AND w.current = 1
            AND s.field_subject_tid IN (" . $baseline_subjects_string . ")
            AND n.nid <> " . $baseline_node->nid;

    $result = db_query($query);
    $subject_nids = array();
    foreach ($result as $row) {
      $subject_nids[$row->nid] = $row->nid;
    }

    // Compare baseline subjects against all other resource nodes that had the same baseline grades
    if ($subject_nids) {
      $baseline_grades_string = implode(',', $baseline_grades);
      if ($baseline_grades) {
        $subject_nids = implode(',', $subject_nids);
        $query = "
            SELECT
              n.nid,
              g.field_grades_tid AS subject
            FROM {node} n
            JOIN {workbench_moderation_node_history} w ON n.nid = w.nid AND n.vid = w.vid
            JOIN {field_data_field_grades} g ON n.nid = g.entity_id AND n.vid = g.revision_id
            WHERE n.type = 'resource'
            AND w.state = 'published'
            AND w.current = 1
            AND n.nid IN (" . $subject_nids . ")
            AND g.field_grades_tid IN (" . $baseline_grades_string . ")
            AND n.nid <> " . $baseline_node->nid;
        $result = db_query($query);
        $grade_nids = array();
        foreach ($result as $row) {
          $grade_nids[$row->nid] = $row->nid;
        }

        // Compare baseline attributes against all other resource nodes that had the same baseline grades and subjects.
        if ($grade_nids) {
          $baseline_attributes_string = implode(',', $baseline_attributes);
          if ($baseline_attributes) {
            $grade_nids = implode(',', $grade_nids);
            $query = "
              SELECT
                n.nid,
                a.field_attributes_tid AS subject
              FROM {node} n
              JOIN {workbench_moderation_node_history} w ON n.nid = w.nid AND n.vid = w.vid
              JOIN {field_data_field_attributes} a ON n.nid = a.entity_id AND n.vid = a.revision_id
              WHERE n.type = 'resource'
              AND w.state = 'published'
              AND w.current = 1
              AND n.nid IN (" . $grade_nids . ")
              AND a.field_attributes_tid IN (" . $baseline_attributes_string . ")
              AND n.nid <> " . $baseline_node->nid;
            $result = db_query($query);
            $attributes_nids = array();
            foreach ($result as $row) {
              $attributes_nids[$row->nid] = $row->nid;
            }

            /**
            * Use the first four metadata elements strictly as filters to create the pool of n resources
            * (meaning that all are equally valid and the only rule is that a related resource has at least one
            * match on each of the three attributes), then sort that pool by ratings to get an overall order
            * In this scenario, the ultimate display order is R5, R1 and no other resources
            * Reasoning: both R1 and R5 have at least one match in each category, and R5 has a higher total
            * ratings than R1 since R1 has no reviews.
            */
            // This is the resource pool of nodes.
            if ($attributes_nids) {
              $count = 0;
              foreach ($attributes_nids as $nid) {
                if ($count >= 8) {
                  break;
                }

                $query = "SELECT sl.field_student_learning_rating AS learning,
                          pd.field_pro_dev_rating AS pro_dev,
                          eu.field_ease_use_rating AS ease_use
                          FROM {eck_review} r
                          JOIN {field_data_field_student_learning} sl ON r.id = sl.entity_id
                          JOIN {field_data_field_pro_dev} pd ON r.id = pd.entity_id
                          JOIN {field_data_field_ease_use} eu ON r.id = eu.entity_id
                          WHERE r.node_id = " . $nid;
                $result = db_query($query);
                if ($result->rowCount()) {
                  foreach ($result as $row) {
                    $total = $row->learning + $row->pro_dev + $row->ease_use;
                    $related_resources[$nid] = $total;
                  }
                }
                else {
                  $related_resources[$nid] = 0;
                }
                $count++;
              }
            }
          }
        }
      }
    }
  }

  // sort related resources by score.
  if (count($related_resources) > 0) {
    asort($related_resources);
  }

  return $related_resources;
}

/**
 * Builds out the resource card.
 *
 * @param $related_resources
 * @return string
 */
function sbac_share_create_resource_card(&$related_resources) {
  $class = '';
  if (count($related_resources) <= 3) {
    $class = 'static';
  }

  $output = '<div class="resources-container ' . $class . '">';
  $output .= '<ul class="slides">';
  foreach ($related_resources as $nid => $score) {
    $node = node_load($nid);
    if ($node) {
      // hacked all this up into "fields" and some are "classes",
      // did this so i wouldn't have to modify the TPL that much
      // since it was just a copy of the view template.
      $fields = array();
      $fields['nid'] = new stdClass;
      $fields['nid']->raw = $nid;
      $fields['sticky'] = new stdClass;
      $fields['sticky']->raw = $node->sticky;
      $fields['title'] = new stdClass;
      $fields['title']->content = l($node->title, $node->path['alias']);
      $variables = _sbac_resource_grid_image($fields);
      $fields['image'] = $variables['image'];
      $fields['file-type-icon'] = $variables['file-type-icon'];
      $fields['field_alt_body'] = new stdClass;
      $body = (isset($node->field_alt_body['und'][0]['value']) ? $node->field_alt_body['und'][0]['value'] : '');
      $fields['field_alt_body']->content = sbac_resource_truncate($body, 140);
      $fields['state'] = new stdClass;
      $fields['state']->raw = 'published';
      $fields['views'] = (isset($node->field_unique_views['und'][0]['values']) ? $node->field_unique_views['und'][0]['values'] : 0);
      $fields['downloads'] = (isset($node->field_asset_downloads['und'][0]['values']) ? $node->field_asset_downloads['und'][0]['values'] : 0);
      $fields['collaborators'] = 'N Collaborations';
      $fields['subject'] = sbac_share_get_field_terms($node->field_subject);
      $fields['grades'] = sbac_share_get_field_terms($node->field_grades);
      $fields['media_types'] = sbac_share_get_field_terms($node->field_digital_media_type);
      $output .= '<li>' . theme('sbac_resource_card', array('fields' => $fields)) . '</li>';
    }
  }
  $output .= '</ul>';
  $output .= '</div>';
  return $output;
}

/**
 * Helper function to retreive the term name(s).
 *
 * @param $field
 * @return string
 *
 */
function sbac_share_get_field_terms($field) {
  $term_names = array();
  foreach ($field['und'] as $key => $tid) {
    $term = taxonomy_term_load($tid['tid']);
    $term_names[] = $term->name;
  }

  $terms = '';
  if ($term_names) {
    $terms = implode(', ', $term_names);
  }
  return $terms;
}

/**
 * Implements hook_user_operations().
 *
 * @return mixed
 */
function sbac_resource_user_operations() {
  $operations['sbac_resource_rebuild_permssions'] = array(
    'label' => t('Rebuild User Permissions'),
    'callback' => 'sbac_resource_rebuild_node_permissions',
  );
  return $operations;
}

/**
 * Rebuilds the node access permissions.
 */
function sbac_resource_rebuild_node_permissions() {
  node_access_rebuild(TRUE);
}

/**
 * Access callback for my resources menu item.
 *
 * @return bool
 */
function sbac_resource_my_resources_access_callback() {
  global $user;
  if (in_array('resource contributor', $user->roles)) {
    return TRUE;
  }
  if ($user->uid == 1 || in_array('DLRB member', $user->roles) || in_array('digital library administrator', $user->roles) || in_array('system administrator', $user->roles)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Access callback for resource review menu item.
 *
 * @return bool
 */
function sbac_resource_resource_review_access_callback() {
  global $user;
  if (in_array('resource reviewer', $user->roles)) {
    return TRUE;
  }
  if (in_array('resource publisher', $user->roles)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Access callback for menu item.
 *
 * @param $node_type
 * @return bool
 */
function sbac_resource_form_messages_access($node_type) {
  if ($node_type->type == 'resource') {
    return user_access('administer site configuration');
  }
  return FALSE;
}

/**
 * Implementation of hook_preprocess_node()
 *
 * @param $vars
 */
function sbac_resource_preprocess_node(&$vars) {
  if ($vars['type'] == 'resource') {
    drupal_set_title($vars['title']);
    drupal_add_js(libraries_get_path('jwplayer') . '/jwplayer.js');
    drupal_add_js(drupal_get_path('module', 'sbac_resource') . '/js/sbac_resource.node.js');
    $vars['author'] = ''; $vars['license'] = ''; $vars['owner'] = ''; $vars['resource_type'] = '';
    if (isset($vars['field_focus'][0]['tid'])) {
      $resource_types = array();
      foreach ($vars['field_focus'] as $key => $term) {
        $resource_types[] = $term['taxonomy_term']->name;
      }
      $vars['resource_type'] = implode(', ', $resource_types);
    }
    if (isset($vars['field_author'][0]['safe_value'])) {
      $vars['author'] = htmlspecialchars_decode($vars['field_author'][0]['safe_value']);
    }
    if (isset($vars['field_publisher']['und'][0]['safe_value'])) {
      $vars['owner'] = htmlspecialchars_decode($vars['field_publisher']['und'][0]['safe_value']);
    }
    if (isset($vars['field_license'][0]['taxonomy_term']->name)) {
      $vars['license'] = $vars['field_license'][0]['taxonomy_term']->name;
    }
    // Edit link for DLRB member's.
    global $user;
    if ($user->uid == 1 || in_array('DLRB member', $user->roles) || in_array('digital library administrator', $user->roles) || in_array('system administrator', $user->roles)) {
      $url = url('node/' . $vars['nid'] . '/edit', array('absolute' => TRUE));
      $vars['edit_link'] = l('Edit', $url, array('attributes' => array('class' => array('medium', 'button'))));
    }
    // Documents
    if (isset($vars['document'][0]) || isset($vars['document']['html5'])) {
      // Determine the file type, load up the correct video player, doc viewer or image viewer.
      $viewer = _sbac_resource_preview_content($vars);
      $materials = _sbac_resource_preview_materials($vars);
      if (isset($vars['document']) && sbac_media_downloadable_scheme($vars['document']) && !in_array(SBAC_SHARE_GUEST, $user->roles)) {
        $vars['download'] = l('Download', 'sbac-media/download/' . $vars['nid'], array('attributes' => array('class' => 'button small right')));
      }
      $vars['viewer'] = $viewer['viewer'];
      $vars['viewer_filename'] = $viewer['viewer_filename'];
      $vars['materials'] = $materials;
    }
  }
}

/**
 * Creates the preview content.
 *
 * @param $vars
 * @return string
 */
function _sbac_resource_preview_content(&$vars) {
  $viewer = NULL;
  $html5 = FALSE;
  if (isset($vars['document']['html5'])) {
    $html5 = TRUE;
    $media = $vars['document']['html5'];
    $file = file_load($media->fid);
    $directory = "private://html5/" . floor($vars['nid']/32000) . "/" . $vars['nid'];
    $real_path = drupal_realpath($directory) . '/' . $file->filename;
    $file_data = pathinfo($real_path);
    $source = $directory . '/html5_module/dlcomponents/CoverPage.html';
    $url = file_create_url($source);
    $viewer['viewer_filename'] = ucwords($file_data['filename']);
    $viewer['viewer'] = '<iframe src="' . $url . '" width="850" height="600" style="border: none;"></iframe>';
  }

  if (isset($vars['document'][0]) && $vars['document'][0] && !$html5) {
    $media = $vars['document'][0];
    $type = _sbac_resource_determine_type($media);
    $viewer['viewer_filename'] = $media->filename;
    if ($media->transcript) {
      $viewer['viewer_filename'] .= ' (Transcipt Included)';
    }

    $uri = NULL;
    if ($media->fid) {
      $file = file_load($media->fid);
      $url = file_create_url($file->uri);
      $uri = $file->uri;
    }
    else {
      $url = sbac_media_create_embed_url($media);
    }

    if ($uri) {
      $real_path = drupal_realpath($uri);
      if (!file_exists($real_path)) {
        $url = drupal_get_path('module', 'sbac_resource') . '/images/no-preview.jpg';
        $viewer['viewer'] = theme('image', array('path' => $url));
        return $viewer;
      }
    }

    if ($type == 'document') {
      $google_url = 'http://docs.google.com/viewer';
      if (isset($_SERVER['HTTPS'])) {
        $google_url = 'https://docs.google.com/viewer';
      }
      $viewer['viewer'] = '<iframe src="' . $google_url . '?url=' . $url . '&embedded=true" width="850" height="400" style="border: none;"></iframe>';
    }
    else if ($type == 'video') {
      $jwplayer = 'jQuery(document).ready(function () {jwplayer("sbac-jwplayer").setup({ file: "' . $url . '", height: 400, width: 850});});';
      drupal_add_js($jwplayer, array('type' => 'inline', 'weight' => 999));
      $viewer['viewer'] = '<div id="sbac-jwplayer"></div>';
    }
    else if ($type == 'image') {
      $viewer['viewer'] = theme('image', array('path' => $url, 'width' => 850, 'height' => 400));
    }
    else if ($type == 'schooltube') {
      $viewer['viewer'] = '<div class="flex-video"><iframe width="500" height="375" src="' . $url . '" frameborder="0" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" webkitallowfullscreen="webkitallowfullscreen"></iframe></div>';
    }
    else if ($type == 'teachertube') {
      $viewer['viewer'] = '<div class="flex-video"><iframe width="560" height="315" src="' . $url . '" frameborder="0" allowfullscreen/></iframe></div>';
    }
    else if ($type == 'slideshare') {
      $viewer['viewer'] = '<div class="flex-video"><iframe src="' . $url . '" width="427" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe></div>';
    }
    else if ($type == 'vimeo') {
      $viewer['viewer'] = '<div class="flex-video"><iframe src="' . $url . '" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>';
    }
    else if ($type == 'youtube') {
      $url .= '?rel=0'; // Disable related videos.
      $viewer['viewer'] = '<div class="flex-video"><iframe width="560" height="315" src="' . $url . '" frameborder="0" allowfullscreen></iframe></div>';
    }
    else {
      $url = drupal_get_path('module', 'sbac_resource') . '/images/no-preview.jpg';
      $viewer['viewer'] = theme('image', array('path' => $url));
    }
  }
  return $viewer;
}

/**
 * Creates the materials dropdown.
 *
 * @param $vars
 * @return array
 */
function _sbac_resource_preview_materials(&$vars) {
  $materials = '';
  $material_urls = array();

  if (isset($vars['document']['html5'])) {
    $type = 'html5';
    $media = $vars['document']['html5'];
    $file = file_load($media->fid);
    $directory = "private://html5/" . floor($vars['nid']/32000) . "/" . $vars['nid'];
    $real_path = drupal_realpath($directory) . '/' . $file->filename;
    $file_data = pathinfo($real_path);
    $source = $directory . '/html5_module/dlcomponents/CoverPage.html';
    $url = file_create_url($source);
    $material_urls[] = l(ucwords($file_data['filename']), $url, array('attributes' => array('sbac-type' => $type)));
  }

  if (isset($vars['document'][0])) {
    foreach ($vars['document'] as $key => $media) {
      if (is_numeric($key)) {
        $type = _sbac_resource_determine_type($media);
        $uri = NULL;
        if ($type == 'none') {
          $url = drupal_get_path('module', 'sbac_resource') . '/images/no-preview.jpg';
        }
        else if ($media->fid) {
          $file = file_load($media->fid);
          $url = file_create_url($file->uri);
          $uri = $file->uri;
        }
        else {
          $url = sbac_media_create_embed_url($media);
        }

        if ($uri) {
          $real_path = drupal_realpath($uri);
          if (!file_exists($real_path)) {
            $url = drupal_get_path('module', 'sbac_resource') . '/images/no-preview.jpg';
            $type = 'not-found';
          }
        }

        $transcript = 0;
        if ($media->transcript) {
          $transcript = 1;
        }

        // check to see whether its public scheme or not, if so not external
        if ($media->fid) {
          $material_urls[] = l(ucwords($media->filename), $url, array('attributes' => array('sbac-type' => $type, 'transcript' => $transcript)));
        }
        else { // embedded media
          if (strpos($media->embed_url, 'youtube')) {
            $url .= '?rel=0';
          }
          $material_urls[] = l(ucwords($media->filename), $url, array('attributes' => array('sbac-type' => $type, 'transcript' => $transcript), 'absolute' => TRUE, 'external' => TRUE));
        }
      }
    }
  }

  if ($material_urls) {
    $materials = '<a class="button small arrow sbac-materials-dropdown" data-dropdown="sbac-materials">'. t('View All Materials'). '<span></span></a>';
    $materials .= theme('item_list', array(
      'items' => $material_urls,
      'attributes' => array(
        'class' => 'materials-dropdown f-dropdown',
        'id' => 'sbac-materials'
      )
    ));
  }

  return $materials;
}

/**
 * Creates the resource media variables.
 *
 * @param $url
 * @param $file
 * @return string
 */
function _sbac_resource_determine_type($media, $return_embed = FALSE) {
  if (!$media->document_id && !$media->fid) {
    $type = _sbac_resource_determine_media($media, $return_embed);
  }
  else {
    $ext = pathinfo($media->filename, PATHINFO_EXTENSION);
    $type = _sbac_resource_determine_extension($ext);
  }
  return $type;
}

/**
 * Determine the media type based on URL.
 *
 * @param $file object
 * @return string
 */
function _sbac_resource_determine_media($media, $return_embed = FALSE) {
  $type = 'embed';
  if ($return_embed) {
    return $type;
  }
  $embedded_video_source = $media->embed_url;
  if (strpos($embedded_video_source, 'schooltube') !== FALSE) {
    $type = 'schooltube';
  }
  if (strpos($embedded_video_source, 'teachertube') !== FALSE) {
    $type = 'teachertube';
  }
  if (strpos($embedded_video_source, 'slideshare') !== FALSE) {
    $type = 'slideshare';
  }
  if (strpos($embedded_video_source, 'youtube') !== FALSE) {
    $type = 'youtube';
  }
  if (strpos($embedded_video_source, 'vimeo') !== FALSE) {
    $type = 'vimeo';
  }
  return $type;
}

/**
 * Determine the filename extension.
 *
 * @param $ext
 * @return string
 */
function _sbac_resource_determine_extension($ext) {
  $media = 'document';

  switch (strtolower($ext)) {
    case 'txt';
    case 'doc';
    case 'docx';
    case 'pdf';
    case 'xls';
    case 'xlsx';
    case 'pptx';
    case 'ppt';
    case 'odt';
    case 'odp';
    case 'ods';
      $media = 'document';
      break;
    case 'mp4';
    case 'mov';
    case 'mp3';
    case 'aac';
      $media = 'video';
      break;
    case 'png';
    case 'jpg';
    case 'jpeg';
      $media = 'image';
      break;
    case 'mpg';
    case 'avi';
      $media = 'none';
      break;
  }
  return $media;
}

/**
 * Determine the filename extension.
 *
 * @param $ext
 * @return string
 */
function _sbac_resource_determine_file_type_icon($ext) {
  $media = 'document';

  switch (strtolower($ext)) {
    case 'txt';
    case 'doc';
    case 'docx';
      $media = 'doc';
      break;
    case 'pdf';
      $media = 'pdf';
      break;
    case 'xls';
    case 'xlsx';
      $media = 'xls';
      break;
    case 'pptx';
    case 'ppt';
      $media = 'ppt';
      break;
    case 'mp4';
    case 'mpg';
    case 'mov';
    case 'avi';
    case 'mp3';
    case 'aac';
      $media = 'video';
      break;
    case 'png';
    case 'jpg';
    case 'jpeg';
      $media = 'image';
      break;
  }

  return $media;
}

/**
 * Implementation of hook_preprocess_page()
 *
 * @param $vars
 */
function sbac_resource_preprocess_page(&$vars) {
  $vars['html5'] = FALSE;
  if (isset($vars['node']) && $vars['node']->type == 'resource') {
    if (isset($vars['page']['#type']) && $vars['page']['#type'] == 'page') {
      unset($vars['tabs']);
      $vars['title'] = $vars['node']->title;
      if (isset($vars['node']->field_html5['und'][0]['value']) && $vars['node']->field_html5['und'][0]['value'] && arg(2) != 'edit') {
        $vars['html5'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_preprocess_html().
 *
 * Determine the page display and toss a class on the body.
 *
 * @param $vars
 */
function sbac_resource_preprocess_html(&$vars) {
  if (arg(0) == 'digital-library-resources' || arg(0) == 'my-resources' || arg(0) == 'resource-review') {
    $display = sbac_resource_determine_grid_or_list();
    if ($display == 'grid_view') {
      $vars['classes_array'][] = 'grid-view';
    }
    else {
      $vars['classes_array'][] = 'list-view';
    }
  }
}

/**
 * overide theme_status_messages, in function check if yours, else call theme_status_messages or soemthing
 *
 * @param $theme_registry
 */
 function sbac_resource_theme_registry_alter(&$theme_registry) {
   if (isset($theme_registry['status_messages'])) {
     $theme_registry['status_messages']['function'] = 'sbac_resource_status_messages';
   }
 }

/**
 *
 *
 * @param $variables
 * @return string
 */
function sbac_resource_status_messages($variables) {
  $output = '';
  $structured_messages = array();
  $messages = drupal_get_messages('sbac_resource_error');
  if (isset($messages['sbac_resource_error'])) {
    foreach ($messages['sbac_resource_error'] as $message) {
      $elements = explode(':', $message);
      $section = $elements[0];
      $field = $elements[1];
      $error_type = $elements[2];
      $error_message = $elements[3];
      if (isset($elements[4])) {
        $error_message .= ': ' . $elements[4];
      }
      $structured_messages[$section][$error_type][$field] = $error_message;
    }
  }

  $final_messages = array();
  if ($structured_messages) {
    foreach ($structured_messages as $section => $field_errors) {
      if (count($field_errors['group']) > 1) { // Group is needed, create structure, extra Parent label
        foreach ($field_errors['group'] as $field => $error) {
          $final_messages[$section]['messages'][] = $error;
          $final_messages[$section]['group'] = TRUE;
        }
      }
      else {
        $single_message = array_shift($field_errors['single']);
        $final_messages[$section]['messages'][] = $single_message;
      }
    }

    if ($final_messages) {
      $output = sbac_resource_status_messages_output($variables, $final_messages);
    }
  }

  if (!$final_messages) {
    $output = sbac_status_messages($variables);
  }

  return $output;
}

/**
 * Takes the final array structure from sbac_resource_status_messages
 * and builds the desired output.
 *
 * @param $variables
 * @param $final_messages
 */
function sbac_resource_status_messages_output($variables, $final_messages) {
  $output = '';
  foreach ($final_messages as $section => $messages) {
    $header = $section;
    if (isset($messages['group'])) {
      $header = "Please correct the following to continue: ";
    }

    $output .= "<div class='sbac-resource-alert-box alert-box alert'>\n";
    if (isset($messages['group'])) {
      $output .= "<h2 class='sbac-resource-error-section'>" . ucwords($header) . "</h2>\n";
    }
    $output .= " <ul>\n";
    foreach ($messages['messages'] as $message) {
      $output .= '  <li>' . $message . "</li>\n";
    }
    $output .= " </ul>\n";
    $output .= "</div>\n";
  }
  return $output;
}

/**
 * Override drupal core messages with zurb foundation alert-box messages.
 * Customize the colors within the _settings.scss file
 *
 * http://foundation.zurb.com/docs/elements.php#panelEx
 */
function sbac_status_messages($variables) {
  $display = $variables['display'];
  $output = '';

  $status_heading = array(
    'error' => t('Error message'),
    'status' => t('Status message'),
    'warning' => t('Warning message'),
  );
  $status_mapping = array(
    'error' => 'alert',
    'success' => 'success',
    'warning' => 'secondary'
  );
  $error_messages = drupal_get_messages($display);
  foreach ($error_messages as $type => $messages) {
    if ($messages) {
      $type_output = '';
      if (isset($status_mapping[$type])) {
        $type_output .= "<div class=\"drupal-alert-box alert-box $status_mapping[$type]\">\n";
      }
      else {
        $type_output .= "<div class=\"sbac-alert-box alert-box\">\n";
      }

      if (!empty($status_heading[$type])) {
        $type_output .= '<h2 class="element-invisible">' . $status_heading[$type] . "</h2>\n";
      }

      $added_message = FALSE;
      if (count($messages) > 1) {
        $type_output .= " <ul>\n";
        foreach ($messages as $message) {
          if ($message == 'Content permissions have been rebuilt.') {
            continue;
          }
          $type_output .= '  <li>' . $message . "</li>\n";
          $added_message = TRUE;
        }
        $type_output .= " </ul>\n";
      }
      elseif ($messages[0] != 'Content permissions have been rebuilt.') {
        $type_output .= $messages[0];
        $added_message = TRUE;
      }
      $type_output .= "</div>\n";

      if ($added_message) {
        $output .= $type_output;
      }
    }
  }
  return $output;
}

/**
 * Implements hook_node_load().
 *
 * @param $nodes
 * @param $types
 */
function sbac_resource_node_load($nodes, $types) {
  //make sure we are only viewing through the content/* path
  global $user;
  foreach ($nodes as $node) {
    //make sure we are looking at a node along the node path and it is published before we start to count views
    if (match_uri('node/[0-9]+') && $node->type == 'resource' && $node->status == '1') {
      //update the raw data table
      $query = "insert into node_user_paradata (
						uid,
						nid,
						hits)
					values (
						" . $user->uid . ",
						" . $node->nid . ",
						1)
					on duplicate key
						update hits = hits + 1";
      $result = db_query($query);
      //send the denormed data to the node
      $query = "select sum(hits) as hits, count(distinct(uid)) as unique_hits from node_user_paradata where nid=" . $node->nid;
      $result = db_query($query);
      $thisrow = $result->fetchAssoc();
      $node->field_total_views[LANGUAGE_NONE] = array(0 => array('value' => $thisrow['hits']));
      $node->field_unique_views[LANGUAGE_NONE] = array(0 => array('value' => $thisrow['unique_hits']));
      entity_save_field(array('field_total_views', 'field_unique_views'), $node, 'node', $node->nid);
    }

    // Load all media entities and attach them to the resource.
    if ($node->type == 'resource') {
      $media_items = sbac_media_load_items($node->nid);
      $node->document = $media_items;

      $html5_item = sbac_media_load_html5_item($node->nid);
      if ($html5_item !== FALSE) {
        $node->document['html5'] = $html5_item;
      }
    }
  }
}

/**
 * Implements hook_node_delete().
 *
 * @param $node, $i = file index
 */
function sbac_resource_node_delete($node) {
//  $i = 0;
//  if (isset($node->field_file['und'])) {
//    while ($i < count($node->field_file['und'])) {
//  	  if (isset($node->field_document_id['und'][$i]['value']) && $node->field_document_id['und'][$i]['value']) {
//  		  sbac_resource_delete_file_from_cmis($node->field_document_id['und'][$i]['value'], $i);
//  		  unset($node->field_document_id['und'][$i]);
//  	  }
//
//  	  $i++;
//    }
//  }
}

/**
 * The state of the revision before the transition occurred.
 * @param $node, $i = file index
 */
function sbac_resource_delete_file_from_cmis($document_id, $i)
{
  module_load_include('api.inc', 'cmis');
  try {
    $start = microtime_float();

    $repository = cmis_get_repository();
    $cmis_object_properties = cmisapi_getProperties($repository->repositoryId, $document_id);
    cmisapi_deleteObject($repository->repositoryId, $cmis_object_properties->id);

    $end = microtime_float();
    $difference = $end - $start;

    watchdog('sbac', 'did delete in: ' . $difference . ' seconds');
  }
  catch (CMISException $e) {
    // cmis_error_handler('sbac_documents_delete_document', $e);
  }
}

/**
 * Implemenets hook_workbench_moderation_transition().
 *
 * @param $new_state
 *  The new state of the revision.
 */
function sbac_resource_workbench_moderation_transition($node, $previous_state, $new_state) {
  if ($node->type == 'resource' && $new_state != 'removed') {
    // Necassary to override workbench moderation into publishing the node. Line 1602, function
    // workbench_moderation_node_data(), they query the DB directly to find out if there is a
    // published node. I bruce lee the publish status here.
    db_query('UPDATE {node} SET status = 1 WHERE nid = :nid', array(':nid' => $node->nid));
    db_query('UPDATE {node_revision} SET status = 1 WHERE nid = :nid AND vid = :vid', array(':nid' => $node->nid, ':vid' => $node->vid));
  }
  else if ($node->type == 'resource' && $new_state == 'removed') {
    $node->status = 0;
  }

  // issue, i need to create records for everyone during state transitions, could limit this to "being_reviewed" and "approved".
  // need to put logic in that loops around users for a given role and creates records based on feedback states.
  // this will also be your update script.
  if ($node->type == 'resource') {
    sbac_resource_save_current_state($node);
  }
}

/**
 * Saves the current state to a separate table.
 *
 * @param $node
 */
function sbac_resource_save_current_state($node) {
  if ($node->type == 'resource') {
    if (isset($node->workbench_moderation['current']->state) && $node->workbench_moderation['current']->state == 'needs_review') {
      sbac_resource_save_resource_state_for_all_role($node, 'resource reviewer', 'needs_review');
    }

    if (isset($node->workbench_moderation['current']->state) && $node->workbench_moderation['current']->state == 'being_reviewed') {
      // new one, if gate keeping in progress, give access to that user, no one else
      $gate_keeper = _sbac_resource_determine_feedback($node->nid, 'gate_keeper', FALSE, 1, 0, 1, 'single');
      if ($gate_keeper) {
        $entity = NULL;
        $new_record = sbac_resource_get_state($node->nid, $gate_keeper['uid'], $entity);
        $entity->state = 'gk_being_reviewed';
        sbac_resource_save_resource_state($entity, $new_record);
        sbac_resource_delete_resource_state_for_all_role($node, 'resource reviewer', $gate_keeper['uid']);
      }
      else {
        // if there is no completed feedback and no current feedback, then its in gk_need_review status
        $completed_feedback = _sbac_resource_determine_feedback($node->nid, 'qc', FALSE, 1, 1, 1, 'set');
        $current_review = _sbac_resource_determine_feedback($node->nid, 'qc', FALSE, 1, 0, 1, 'single');
        if (!$completed_feedback && !$current_review) {
          sbac_resource_save_resource_state_for_all_role($node, 'resource reviewer', 'gk_needs_review');
        }
        else {
          // if there is no current review, or completed reviews is less then 3
          if (count($completed_feedback) == 2 && $current_review) {
            $entity = NULL;
            $new_record = sbac_resource_get_state($node->nid, $current_review['uid'], $entity);
            $entity->state = 'qc_being_reviewed';
            sbac_resource_save_resource_state($entity, $new_record);
            sbac_resource_delete_resource_state_for_all_role($node->nid, 'resource reviewer', $current_review['uid']);
          }
          else {
            // everyone has access and is set to needs review
            sbac_resource_save_resource_state_for_all_role($node, 'resource reviewer', 'qc_needs_review');
            // if there is current reviews, tag them correctly
            $current_reviews = _sbac_resource_determine_feedback($node->nid, 'qc', FALSE, 1, 0, 1, 'set');
            foreach ($current_reviews as $current_review) {
              $entity = NULL;
              $new_record = sbac_resource_get_state($node->nid, $current_review->uid, $entity);
              $entity->state = 'qc_being_reviewed';
              sbac_resource_save_resource_state($entity, $new_record);
            }
          }

          // if there are completed reviews, delete the records, the user can not see it anymore.
          foreach ($completed_feedback as $complete_feedback) {
            $entity = NULL;
            $new_record = sbac_resource_get_state($node->nid, $complete_feedback->uid, $entity);
            sbac_resource_delete_resource_state($entity);
          }
        }
      }
    }

    if (isset($node->workbench_moderation['current']->state) && $node->workbench_moderation['current']->state == 'approved') {
      $post_review_in_progress = _sbac_resource_determine_feedback($node->nid, 'post', FALSE, 1, 0, 1, 'single');
      if ($post_review_in_progress) {
        $entity = NULL;
        $new_record = sbac_resource_get_state($node->nid, $post_review_in_progress['uid'], $entity);
        $entity->state = 'post_being_reviewed';
        sbac_resource_save_resource_state($entity, $new_record);
        sbac_resource_delete_resource_state_for_all_role($node, 'resource publisher', $post_review_in_progress['uid']);
      }
      else {
        sbac_resource_save_resource_state_for_all_role($node, 'resource publisher', 'post_needs_review');
      }
    }

    if (isset($node->workbench_moderation['current']->state) &&
      $node->workbench_moderation['current']->state != 'needs_review') {
      sbac_resource_delete_resource_state_for_all_role($node, 'resource reviewer', NULL, array('needs_review'));
    }

    // if the node is in neither state, delete all records associated to this role and node.
    if (isset($node->workbench_moderation['current']->state) &&
      $node->workbench_moderation['current']->state != 'being_reviewed' &&
      $node->workbench_moderation['current']->state != 'needs_review') {
      sbac_resource_delete_resource_state_for_all_role($node, 'resource reviewer', NULL, array('gk_being_reviewed', 'gk_needs_review', 'qc_being_reviewed', 'qc_needs_review'));
    }

    // if the node is in neither state, delete all records associated to this role and node.
    if (isset($node->workbench_moderation['current']->state) &&
      $node->workbench_moderation['current']->state != 'approved') {
      sbac_resource_delete_resource_state_for_all_role($node, 'resource publisher', NULL, array('post_being_reviewed', 'post_needs_review'));
    }
  }
}

/**
 * Implements hook_query_alter().
 *
 * Alters the resource review view since the group by statement doesn't work
 * in the hook_views_query_alter(). This is a bug in views.
 *
 * @param $query
 */
function sbac_resource_query_alter( &$query) {
  if(isset($query->alterMetaData['view']->name) && $query->alterMetaData['view']->name == "resource_review"){
    $query->groupBy("node.nid");
  }
}

/**
 * Get all users by the role name.
 *
 * @param $role_name
 * @return mixed
 */
function sbac_resource_get_users_by_role($role_name) {
  $uids = array();
  // Get role
  $role = user_role_load_by_name($role_name);
  // Query
  $query = "SELECT DISTINCT(ur.uid) FROM {users_roles} AS ur WHERE ur.rid = :rid";
  $result = db_query($query, array(':rid' => $role->rid));
  foreach ($result as $row) {
    $uids[] = $row->uid;
  }
  // Load users.
  $accounts = array();
  $accounts = user_load_multiple($uids);
  return $accounts;
}

/**
 * Inserts / Updates the resource state.
 *
 * @param $entity
 * @param $new_record
 */
function sbac_resource_save_resource_state($entity, $new_record) {
  if ($new_record) {
    drupal_write_record('sbac_node_resource_state', $entity);
  }
  else {
    drupal_write_record('sbac_node_resource_state', $entity, array('nid', 'uid'));
  }
}

/**
 * Loops through all users given a role and saves the new record.
 *
 * @param $node
 * @param $role_name
 * @param $new_state
 * @param null $skip_uids
 */
function sbac_resource_save_resource_state_for_all_role($node, $role_name, $new_state, $skip_uids = NULL) {
  $accounts = sbac_resource_get_users_by_role($role_name);
  foreach ($accounts as $account) {
    if ($skip_uids != NULL) {
      if (is_array($skip_uids) && !in_array($account->uid, $skip_uids)) {
        $entity = NULL;
        $new_record = sbac_resource_get_state($node->nid, $account->uid, $entity);
        $entity->state = $new_state;
        sbac_resource_save_resource_state($entity, $new_record);
      }
    }
    else {
      $entity = NULL;
      $new_record = sbac_resource_get_state($node->nid, $account->uid, $entity);
      $entity->state = $new_state;
      sbac_resource_save_resource_state($entity, $new_record);
    }
  }
}

/**
 * Loops through all users given a role and deletes the record for the given
 * node id. Excluding the uid provided (if one).
 *
 * @param $node
 * @param $role_name
 * @param null $keep_uid
 */
function sbac_resource_delete_resource_state_for_all_role($node, $role_name, $keep_uid = NULL, $states_to_delete = array()) {
  // Sometimes we get an nid string.
  if (!is_object($node)) {
    $node = node_load($node);
  }

  // Remove all other users
  $accounts = sbac_resource_get_users_by_role($role_name);
  foreach ($accounts as $account) {
    if ($keep_uid != NULL) { // if there is uid(s) to keep.
      if (is_array($keep_uid)) { // if the uid(s) is an array
        if (!in_array($account->uid, $keep_uid)) {
          $entity = NULL;
          $new_record = sbac_resource_get_state($node->nid, $account->uid, $entity);
          if ($states_to_delete && in_array($entity->state, $states_to_delete)) { // valid states to delete
            sbac_resource_delete_resource_state($entity, $new_record);
          }
          else if (!$states_to_delete) { // delete all states.
            sbac_resource_delete_resource_state($entity, $new_record);
          }
        }
      }
      else{
        if ($account->uid != $keep_uid) {
          $entity = NULL;
          $new_record = sbac_resource_get_state($node->nid, $account->uid, $entity);
          if ($states_to_delete && in_array($entity->state, $states_to_delete)) {
            sbac_resource_delete_resource_state($entity, $new_record);
          }
          else if (!$states_to_delete) {
            sbac_resource_delete_resource_state($entity, $new_record);
          }
        }
      }
    }
    else {
      $entity = NULL;
      $new_record = sbac_resource_get_state($node->nid, $account->uid, $entity);
      if ($states_to_delete && isset($entity->state) && in_array($entity->state, $states_to_delete)) {
        sbac_resource_delete_resource_state($entity, $new_record);
      }
      else if (!$states_to_delete) {
        sbac_resource_delete_resource_state($entity, $new_record);
      }
    }
  }
}

/**
 * Deletes the resource state for the given UID and NID.
 *
 * @param $entity
 */
function sbac_resource_delete_resource_state($entity) {
  if (!isset($entity->nid) || !$entity->nid) {
    return;
  }
  if (!isset($entity->uid) || !$entity->uid) {
    return;
  }
  if (!isset($entity->state) || !$entity->state) {
    return;
  }
  db_delete('sbac_node_resource_state')
    ->condition('nid', $entity->nid)
    ->condition('uid', $entity->uid)
    ->condition('state', $entity->state)
    ->execute();
}

/**
 * Gets the state object from the custom table.
 *
 * @param $nid
 * @param $uid
 * @param $entity
 * @return bool
 */
function sbac_resource_get_state($nid, $uid, &$entity){
  $query = db_select('sbac_node_resource_state', 'snrs');
  $query->fields('snrs');
  $query->condition('nid', $nid);
  $query->condition('uid', $uid);
  $result = $query->execute()->fetchObject();
  if (!$result) {
    $entity = new stdClass();
    $entity->nid = $nid;
    $entity->uid = $uid;
    $new_record = TRUE;
  }
  else {
    $entity = $result;
    $new_record = FALSE;
  }

  return $new_record;
}

/**
 * Implements hook_node_access_records().
 *
 * @param $node
 */
function sbac_resource_node_access_records($node) {
  if ($node->type == 'resource') {
    $grants = array();
    $restricted = FALSE;

    if (isset($node->workbench_moderation['current']->state) &&
        ($node->workbench_moderation['current']->state == 'creation' ||
         $node->workbench_moderation['current']->state == 'draft' ||
         $node->workbench_moderation['current']->state == 'removed')) {
      $restricted = TRUE;
    }

    // Needs review node access perms.
    if (isset($node->workbench_moderation['current']->state) && $node->workbench_moderation['current']->state == 'needs_review') {
      $accounts = sbac_resource_get_users_by_role('resource reviewer');
      foreach ($accounts as $account) {
        if ($account->uid != $node->uid) { // a reviewer is not able to review the nodes they created.
          $restricted = TRUE;
          $grants[] = array(
            'realm' => 'able_to_review',
            'gid' => $account->uid,
            'grant_view' => 1,
            'grant_update' => 0,
            'grant_delete' => 0,
            'priority' => 0,
          );
        }
      }
    }

    // Being reviewed node access perms.
    if (isset($node->workbench_moderation['current']->state) && $node->workbench_moderation['current']->state == 'being_reviewed') {
      $accounts = sbac_resource_get_users_by_role('resource reviewer');
      if ($accounts) {
        $completed_gk = _sbac_resource_determine_feedback($node->nid, 'gate_keeper', FALSE, 1, 1, 1, 'single');
        if ($completed_gk) {
          $completed_feedback = _sbac_resource_determine_feedback($node->nid, 'qc', FALSE, 1, 1, 1, 'set');
          $current_reviews = _sbac_resource_determine_feedback($node->nid, 'qc', FALSE, 1, 0, 1, 'set');
          // everyone has access when no completed or current review
          if (!$completed_feedback && !$current_reviews) {
            foreach ($accounts as $account) {
              $restricted = TRUE;
              $grants[] = array(
                'realm' => 'able_to_review_qc',
                'gid' => $account->uid,
                'grant_view' => 1,
                'grant_update' => 0,
                'grant_delete' => 0,
                'priority' => 0,
              );
            }
          }

          // everyone has access when the completed = 0 and current reviews <= 3.
          if (!$completed_feedback && $current_reviews && count($current_reviews) <= 3) {
            // if current reviews is less then 3, give access to everyone.
            if (count($current_reviews) < 3) {
              foreach ($accounts as $account) {
                $restricted = TRUE;
                $grants[] = array(
                  'realm' => 'able_to_review_qc',
                  'gid' => $account->uid,
                  'grant_view' => 1,
                  'grant_update' => 0,
                  'grant_delete' => 0,
                  'priority' => 0,
                );
              }
            }

            // if current reviews is 3, give access to only those 3 reviewers.
            if (count($current_reviews) == 3) {
              foreach ($current_reviews as $current_review) {
                $restricted = TRUE;
                $grants[] = array(
                  'realm' => 'able_to_review_qc',
                  'gid' => $current_review->uid,
                  'grant_view' => 1,
                  'grant_update' => 0,
                  'grant_delete' => 0,
                  'priority' => 0,
                );
              }
            }
          }

          // everyone has access except when completed = 3
          if ($completed_feedback && count($completed_feedback) < 3) {
            if ($current_reviews) {
              // everyone has access except when the completed = 1 and current reviews = 2
              if (count($completed_feedback) == 1 && count($current_reviews) == 2) {
                foreach ($current_reviews as $current_review) {
                  $restricted = TRUE;
                  $grants[] = array(
                    'realm' => 'able_to_review_qc',
                    'gid' => $current_review->uid,
                    'grant_view' => 1,
                    'grant_update' => 0,
                    'grant_delete' => 0,
                    'priority' => 0,
                  );
                }
              }
              // everyone has access except when the completed = 2 and current reviews = 1
              else if (count($completed_feedback) == 2 && count($current_reviews) == 1) {
                foreach ($current_reviews as $current_review) {
                  $restricted = TRUE;
                  $grants[] = array(
                    'realm' => 'able_to_review_qc',
                    'gid' => $current_review->uid,
                    'grant_view' => 1,
                    'grant_update' => 0,
                    'grant_delete' => 0,
                    'priority' => 0,
                  );
                }
              }
              else {
                $not_allowed_to_view = array();
                foreach ($completed_feedback as $feedback) {
                  $not_allowed_to_view[] = $feedback->uid;
                }

                foreach ($accounts as $account) {
                  if (!in_array($account->uid, $not_allowed_to_view)) {
                    $restricted = TRUE;
                    $grants[] = array(
                      'realm' => 'able_to_review_qc',
                      'gid' => $account->uid,
                      'grant_view' => 1,
                      'grant_update' => 0,
                      'grant_delete' => 0,
                      'priority' => 0,
                    );
                  }
                }
              }
            }
            else {
              $not_allowed_to_view = array();
              foreach ($completed_feedback as $feedback) {
                $not_allowed_to_view[] = $feedback->uid;
              }

              foreach ($accounts as $account) {
                if (!in_array($account->uid, $not_allowed_to_view)) {
                  $restricted = TRUE;
                  $grants[] = array(
                    'realm' => 'able_to_review_qc',
                    'gid' => $account->uid,
                    'grant_view' => 1,
                    'grant_update' => 0,
                    'grant_delete' => 0,
                    'priority' => 0,
                  );
                }
              }
            }
          }

          // give access to the user who completed the gate keeper too. only if he has not completed the QC though.
          $gate_keeper = _sbac_resource_determine_feedback($node->nid, 'gate_keeper', FALSE, 1, 1, 1, 'single');
          if ($gate_keeper) {
            $current_review = _sbac_resource_determine_feedback($node->nid, 'qc', $gate_keeper['uid'], 1, 1, 1, 'single');
            if (!$current_review) {
              $restricted = TRUE;
              $grants[] = array(
                'realm' => 'completed_gk',
                'gid' => $gate_keeper['uid'],
                'grant_view' => 1,
                'grant_update' => 0,
                'grant_delete' => 0,
                'priority' => 0,
              );
            }
          }
        }
        else {
          // new one, if gate keeping in progress, give access to that user, no one else
          $gate_keeper = _sbac_resource_determine_feedback($node->nid, 'gate_keeper', FALSE, 1, 0, 1, 'single');
          if ($gate_keeper) {
            $restricted = TRUE;
            $grants[] = array(
              'realm' => 'gk_review_in_progress',
              'gid' => $gate_keeper['uid'],
              'grant_view' => 1,
              'grant_update' => 0,
              'grant_delete' => 0,
              'priority' => 0,
            );
          }
          else {
            foreach ($accounts as $account) {
              $restricted = TRUE;
              $grants[] = array(
                'realm' => 'able_to_review_qc',
                'gid' => $account->uid,
                'grant_view' => 1,
                'grant_update' => 0,
                'grant_delete' => 0,
                'priority' => 0,
              );
            }
          }
        }
      }
    }

    // Approved node access perms.
    if (isset($node->workbench_moderation['current']->state) && $node->workbench_moderation['current']->state == 'approved') {
      // check for in progress feedback.
      $in_progress_feedback = _sbac_resource_determine_feedback($node->nid, 'post', FALSE, 1, 0, 1, 'single');
      if ($in_progress_feedback) {
        $restricted = TRUE;
        $grants[] = array(
          'realm' => 'able_to_review_post',
          'gid' => $in_progress_feedback['uid'],
          'grant_view' => 1,
          'grant_update' => 0,
          'grant_delete' => 0,
          'priority' => 0,
        );
      }
      else {
        $accounts = sbac_resource_get_users_by_role('resource publisher');
        foreach ($accounts as $account) {
          $restricted = TRUE;
          $grants[] = array(
            'realm' => 'able_to_review_post',
            'gid' => $account->uid,
            'grant_view' => 1,
            'grant_update' => 0,
            'grant_delete' => 0,
            'priority' => 0,
          );
        }
      }
    }
    // @FIXME
    // This is a workaround since the above code is adding the same UID multiple
    // times for a given grant realm and nid. The {node_access} table
    // has a compund key of nid, gid, and realm, hence the SQL constraint error.
    foreach ($grants as $key => $grant) {
      if ($grant['realm'] == 'able_to_review_qc') {
        $uid = $grant['gid'];
        foreach ($grants as $j => $temp_grant) {
          // Ensure we're not removing the original.
          if ($temp_grant['realm'] == 'able_to_review_qc' && $temp_grant['gid'] == $uid && $j != $key) {
            unset($grants[$j]);
          }
        }
      }
    }
    // This is so the resource contributor can view his own nodes regardless of state.
    if ($restricted) {
      $grants[] = array(
        'realm' => 'node_author',
        'gid' => $node->uid,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );

      return $grants;
    }
  }
}

/**
 * Implements hook_node_grants().
 *
 * @param $account
 * @param $op
 */
function sbac_resource_node_grants($account, $op) {
  if (arg(0) == 'resource-review') {
    if (!in_array('resource contributor', $account->roles)) {
      $grants['node_author'] = array($account->uid);
    }
  }
  else {
    $grants['node_author'] = array($account->uid);
  }

  if (in_array('resource reviewer', $account->roles)) {
    $grants['gk_review_in_progress'] = array($account->uid);
    $grants['able_to_review_qc'] = array($account->uid);
    $grants['completed_gk'] = array($account->uid);
    $grants['able_to_review'] = array($account->uid);
  }

  if (in_array('resource publisher', $account->roles)) {
    $grants['able_to_review_post'] = array($account->uid);
  }
  return $grants;
}

/**
 * Implements hook_node_update();
 *
 * @param $node
 */
function sbac_resource_node_update($node) {
  if ($node->type == 'resource') {
    if (isset($node->workbench_moderation['published'])) {
      $node->workbench_moderation['published']->vid = $node->vid;
    }
  }
}

/**
 * Implements of hook_page_alter().
 *
 * @param $page
 */
function sbac_resource_page_alter(&$page) {
  if (!isset($page['content']['system_main']['#form_id'])) {
  }
  else {
    if (isset($page['content']['system_main']['#form_id']) && $page['content']['system_main']['#form_id'] == 'resource_node_form') {
      $page['help']['system_help']['#markup'] = '';
    }
  }
}

/**
 * Text to display when "Has No License" option is selected on Licensing radio boxes
 * in Resource - Materials
 *
 * @return string
 */
function sbac_resource_licensing_form_has_no_license() {
  $output = '
              <ul>
                <li>Before continuing, you must obtain permission to use the resource in the Digital Library.</li>
                <li>Download, complete and submit the Copyright Clearance Form to resume your submittal.</li>
              </ul>
            ';

  return $output;
}

/**
 * Creates a grid or list button.
 *
 * @return string
 */
function sbac_resource_grid_list_button() {
  switch (arg(0)) {
    case 'my-resources':
      $name = SBAC_RESOURCE_MY_RESOURCES_VIEW_MODE;
      break;
    case 'digital-library-resources':
      $name = SBAC_RESOURCE_DIGITAL_LIBRARY_RESOURCES_VIEW_MODE;
      break;
    case 'resource-review':
      $name = SBAC_RESOURCE_RESOURCE_REVIEW_VIEW_MODE;
      break;
    default:
      $name = SBAC_RESOURCE_DIGITAL_LIBRARY_RESOURCES_VIEW_MODE;
      break;
  }
  $path = arg(0);
  if (isset($_SESSION[$name])) {
    $display_mode = $_SESSION[$name];
    if ($display_mode == 'grid_view') {
      $button = l('List View', $path . '/list', array(
        'absolute' => TRUE,
        'attributes' => array(
          'class' => array('sbac-list-layout')
        )
      ));
    }
    else {
      $button = l('Grid View', $path . '/grid', array(
        'absolute' => TRUE,
        'attributes' => array(
          'class' => array('sbac-grid-layout')
        )
      ));
    }
  }
  else {
    $button = l('List View', $path . '/list', array(
      'absolute' => TRUE,
      'attributes' => array(
        'class' => array('sbac-list-layout')
      )
    ));
    if (arg(1) != NULL && arg(1) == 'list') {
      $button = l('Grid View', $path . '/grid', array(
        'absolute' => TRUE,
        'attributes' => array(
          'class' => array('sbac-grid-layout')
        )
      ));
    }
  }

  return $button;
}

/**
 * Implements hook_block_info().
 *
 */
function sbac_resource_block_info() {
  $blocks['sbac_resource_results_count'] = array(
    'info' => t('Search Results Count'),
    'region' => 'sub-header',
    'pages' => "digital-library-resources*\nmy-resources*\nresource-review*",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -23,
    'status' => 1,
  );

  $blocks['sbac_resource_create_button'] = array(
    'info' => t('Create New Resource'),
    'region' => 'sub-header',
    'pages' => "my-resources*",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'weight' => -22,
    'status' => 1,
  );

  $blocks['sbac_resource_grid_list_button'] = array(
    'info' => t('Grid / List button'),
    'region' => 'search',
    'pages' => "digital-library-resources*\nmy-resources*\nresource-review*",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_NO_CACHE,
    'status' => 1,
    'weight' => 0,
  );

  $blocks['sbac_resource_back_button'] = array(
    'info' => t('Back Button'),
    'region' => 'sub-header',
    'pages' => "content*\nterms-of-service",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'status' => 1,
  );

  $blocks['sbac_resource_dl_sort_form'] = array(
    'info' => t('Sort'),
    'region' => 'sub-header',
    'pages' => "digital-library-resources*\n",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -21,
    'status' => 1,
  );

  $blocks['sbac_resource_rr_sort_form'] = array(
    'info' => t('Sort'),
    'region' => 'sub-header',
    'pages' => "resource-review*\n",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -21,
    'status' => 1,
  );

  $blocks['sbac_resource_mr_sort_form'] = array(
    'info' => t('Sort'),
    'region' => 'sub-header',
    'pages' => "my-resources*\n",
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -21,
    'status' => 1,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 *
 * @return array
 */
function sbac_resource_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'sbac_resource_results_count':
      switch (arg(0)) {
        case 'my-resources':
          $name = SBAC_SEARCH_MY_RESOURCES_COUNT;
          break;
        case 'digital-library-resources':
          $name = SBAC_SEARCH_DIGITAL_LIBRARY_RESOURCES_COUNT;
          break;
        case 'resource-review':
          $name = SBAC_SEARCH_RESOURCE_REVIEW_COUNT;
          break;
        default:
          $name = SBAC_SEARCH_DIGITAL_LIBRARY_RESOURCES_COUNT;
          break;
      }

      $count = 0;
      if (isset($_SESSION[$name])) {
        $count = $_SESSION[$name];
      }
      $block['subject'] = NULL;
      $block['content'] = '<h3 class="left">' . t('Resources (' . $count . ')') . '</h3>';
      break;

    case 'sbac_resource_create_button':
      $block['subject'] = NULL;
      $block['content'] = sbac_resource_create_button();
      break;

    case 'sbac_resource_grid_list_button':
      $block['subject'] = NULL;
      $block['content'] = sbac_resource_grid_list_button();
      break;

    case 'sbac_resource_back_button':
      $block['subject'] = NULL;
      $previous_url = $_SERVER['HTTP_REFERER'];
      global $base_url;
      if (strpos($previous_url, $base_url) !== FALSE) {
        $previous_url = str_replace($base_url, '', $previous_url);
      }
      $block['content'] = '<a onclick="window.history.back(); return false;" href="' . $previous_url . '" class="button">Back</a>';
      break;
    case 'sbac_resource_dl_sort_form':
      $block['subject'] = NULL;
      $block['content'] = drupal_get_form('sbac_resource_digital_library_sort_form');
      break;
    case 'sbac_resource_rr_sort_form':
      $block['subject'] = NULL;
      $block['content'] = drupal_get_form('sbac_resource_resource_review_sort_form');
      break;
    case 'sbac_resource_mr_sort_form':
      $block['subject'] = NULL;
      $block['content'] = drupal_get_form('sbac_resource_my_resources_sort_form');
      break;
  }
  return $block;
}

/**
 * Implements hook_block_info_alter().
 *
 * @param $blocks
 * @param $theme
 * @param $code_blocks
 */
function sbac_resource_block_info_alter(&$blocks, $theme, $code_blocks) {
  $blocks['system']['navigation']['status'] = FALSE;
  $blocks['workbench']['block']['status'] = FALSE;

  if (isset($blocks['sbac_resource']['sbac_resource_results_count']) && $theme == 'SBAC') {
    $blocks['sbac_resource']['sbac_resource_results_count']['pages'] = "digital-library-resources*\nmy-resources*\nresource-review*";
  }
  if (isset($blocks['sbac_resource']['sbac_resource_create_button']) && $theme == 'SBAC') {
    $blocks['sbac_resource']['sbac_resource_create_button']['pages'] = "my-resources*";
  }
  if (isset($blocks['sbac_resource']['sbac_resource_grid_list_button']) && $theme == 'SBAC') {
    $blocks['sbac_resource']['sbac_resource_grid_list_button']['pages'] = "digital-library-resources*\nmy-resources*\nresource-review*";
  }
}

/**
 * Create button
 *
 * @return null|string
 */
function sbac_resource_create_button() {
  global $user;
  $content = NULL;

  // Resource contributor button.
  if (in_array('resource contributor', $user->roles)) {
    $content = l('Create New Resource', 'node/add/resource', array(
      'absolute' => TRUE,
      'attributes' => array('class' => array('small', 'button')),
      'query' => array('destination' => arg(0)),
    ));
  }

  // DLRB admin / member button.
  if ($user->uid == 1 || in_array('DLRB member', $user->roles) || in_array('digital library administrator', $user->roles) || in_array('system administrator', $user->roles)) {
    $create_urls[] = l('Resource', 'node/add/resource', array('attributes' => array('class' => array('create-resource')), 'absolute' => TRUE, 'external' => TRUE, 'query' => array('type' => 'resource')));
    $create_urls[] = l('Content Module', 'node/add/resource', array('attributes' => array('class' => array('create-module')), 'absolute' => TRUE, 'external' => TRUE, 'query' => array('type' => 'module')));
    $content = '<a class="button small arrow sbac-create-resource-dropdown" data-dropdown="sbac-create-resource">'. t('Create'). '<span></span></a>';
    $content .= theme('item_list', array(
      'items' => $create_urls,
      'attributes' => array(
        'class' => 'materials-dropdown f-dropdown',
        'id' => 'sbac-create-resource'
      )
    ));
  }
  return $content;
}

/**
 * Cleans the text and remove's any malicious text.
 *
 * @param $form_state
 */
function sbac_resource_clean_text(&$form_state) {
  foreach ($form_state['values'] as $field_name => $field) {
    if (is_array($field) && isset($field['und'][0]['value']) && $field['und'][0]['value'] != NULL) {
      $form_state['values'][$field_name]['und'][0]['value'] = filter_xss($field['und'][0]['value']);
    }
    if ($field_name == 'title' && $field != NULL) {
      $form_state['values']['title'] = filter_xss($field);
    }
  }
}

/**
 * Determines if the display is grid / list.
 *
 * @param string $page can be 'dl', 'mr' or 'rr' (for each page).
 * @return string
 */
function sbac_resource_determine_grid_or_list() {
  switch (arg(0)) {
    case 'my-resources':
      $name = SBAC_RESOURCE_MY_RESOURCES_VIEW_MODE;
      break;
    case 'digital-library-resources':
      $name = SBAC_RESOURCE_DIGITAL_LIBRARY_RESOURCES_VIEW_MODE;
      break;
    case 'resource-review':
      $name = SBAC_RESOURCE_RESOURCE_REVIEW_VIEW_MODE;
      break;
    default:
      $name = SBAC_RESOURCE_DIGITAL_LIBRARY_RESOURCES_VIEW_MODE;
      break;
  }

  if (isset($_SESSION[$name])) {
    $display = $_SESSION[$name];
    if (arg(1) == 'list') {
      $display = 'list_view';
    }
    else {
      if (arg(1) == 'grid') {
        $display = 'grid_view';
      }
    }
    $_SESSION[$name] = $display;
  }
  else {
    // By default show grid layout with link to list layout
    $display = 'grid_view';
    if (arg(1) == 'list') {
      $display = 'list_view';
    }
    // Add session variable to persist for users session.
    $_SESSION[$name] = $display;
  }
  return $display;
}

/**
 * Truncates Resources.
 *
 * @param $html
 * @param int $maxLength
 * @return string
 */
function sbac_resource_truncate($html, $maxLength = 100) {
  mb_internal_encoding("UTF-8");
  $printedLength = 0;
  $position = 0;
  $tags = array();
  $newContent = '';

  $html = $content = preg_replace("/<img[^>]+\>/i", "", $html);

  while ($printedLength < $maxLength && preg_match('{</?([a-z]+)[^>]*>|&#?[a-zA-Z0-9]+;}', $html, $match, PREG_OFFSET_CAPTURE, $position)) {
    list($tag, $tagPosition) = $match[0];
    // Print text leading up to the tag.
    $str = mb_strcut($html, $position, $tagPosition - $position);
    if ($printedLength + mb_strlen($str) > $maxLength) {
      $newstr = mb_strcut($str, 0, $maxLength - $printedLength);
      $newstr = preg_replace('~\s+\S+$~', '', $newstr);
      $newContent .= $newstr;
      $printedLength = $maxLength;
      break;
    }
    $newContent .= $str;
    $printedLength += mb_strlen($str);
    if ($tag[0] == '&') {
      // Handle the entity.
      $newContent .= $tag;
      $printedLength++;
    }
    else {
      // Handle the tag.
      $tagName = $match[1][0];
      if ($tag[1] == '/') {
        // This is a closing tag.
        $openingTag = array_pop($tags);
        assert($openingTag == $tagName); // check that tags are properly nested.
        $newContent .= $tag;
      }
      else {
        if ($tag[mb_strlen($tag) - 2] == '/') {
          // Self-closing tag.
          $newContent .= $tag;
        }
        else {
          // Opening tag.
          $newContent .= $tag;
          $tags[] = $tagName;
        }
      }
    }

    // Continue after the tag.
    $position = $tagPosition + mb_strlen($tag);
  }

  // Print any remaining text.
  if ($printedLength < $maxLength && $position < mb_strlen($html)) {
    $newstr = mb_strcut($html, $position, $maxLength - $printedLength);
    $newstr = preg_replace('~\s+\S+$~', '', $newstr);
    $newContent .= $newstr;
  }

  // Close any open tags.
  while (!empty($tags)) {
    $newContent .= sprintf('</%s>', array_pop($tags));
  }

  return $newContent;
}

function sbac_resource_update_average_rating_score($nid) {
  // Initialize variables.
  $entity_type = 'review';
  $all_reviews = array();
  $scores = array();

  // Query all reviews for the node.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', $entity_type)
    ->entityCondition('bundle', 'end_use')
    ->propertyCondition('node_id', $nid, '=');
  $result = $query->execute();
  if ($result[$entity_type]) {
    $review_ids = array_keys($result[$entity_type]);
    $all_reviews = entity_load($entity_type, $review_ids);
  }

  // Loop through results and pull the avg score value for each review.
  if (!empty($all_reviews)) {
    foreach ($all_reviews as $ent_id => $review) {
      $review_data = entity_metadata_wrapper($entity_type, $review);
      if (isset($review_data->field_avg_rating)) {
        $scores[$ent_id] = $review_data->field_avg_rating->value();
      }
    }
  }

  $overall_avg = 0;
  if (!empty($scores)) {
    $overall_total = 0;
    foreach ($scores as $score) {
      $overall_total += $score;
    }
    $overall_avg = $overall_total / count($scores);
  }

  $resource_node = node_load($nid);
  if (!empty($resource_node)) {
    // Cant do full node save, workbench moderation doesnt like it.
    $resource_node->field_node_avg_rating[LANGUAGE_NONE][0]['value'] = $overall_avg;
    entity_save_field(array('field_node_avg_rating'), $resource_node, 'node', $nid);
  }
}
