<?php
/**
 * @file
 * sbac_authorized_domains.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function sbac_authorized_domains_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'authorized_domains-authorized_domains-field_district'.
  $field_instances['authorized_domains-authorized_domains-field_district'] = array(
    'bundle' => 'authorized_domains',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'authorized_domains',
    'field_name' => 'field_district',
    'label' => 'District',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'apply_chosen' => '',
        'label_help_description' => '',
      ),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'authorized_domains-authorized_domains-field_domain'.
  $field_instances['authorized_domains-authorized_domains-field_domain'] = array(
    'bundle' => 'authorized_domains',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'authorized_domains',
    'field_name' => 'field_domain',
    'label' => 'Domain',
    'profanity' => 0,
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'label_help_description' => '',
        'maxlength_js' => 0,
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
    'xss' => 0,
  );

  // Exported field_instance:
  // 'authorized_domains-authorized_domains-field_domain_state'.
  $field_instances['authorized_domains-authorized_domains-field_domain_state'] = array(
    'bundle' => 'authorized_domains',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'authorized_domains',
    'field_name' => 'field_domain_state',
    'label' => 'State',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'apply_chosen' => 0,
        'label_help_description' => '',
      ),
      'type' => 'options_select',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('District');
  t('Domain');
  t('State');

  return $field_instances;
}
