#!/bin/bash

cd $(dirname $0)

. ./.env

TTY=""
if [ "$1" == "-t" ]; then
  TTY=$1; shift
fi

exec docker run --net=${COMPOSE_PROJECT_NAME}_default --rm -i $TTY \
    --volumes-from "${COMPOSE_PROJECT_NAME}_phpfpm_1" \
    -e "MYSQL_DATABASE=${MYSQL_DATABASE}" \
    -e "MYSQL_USER=${MYSQL_USER}" \
    -e "MYSQL_PASSWORD=${MYSQL_PASSWORD}" \
    -e "MYSQL_HOST=db" \
    -e "SOLR_HOST=solr" \
    -e "CMS_DEPLOYMENT=${CMS_DEPLOYMENT}" \
    -e "CMS_ENVIRONMENT=${CMS_ENVIRONMENT}" \
    gened/drush -r /var/www/html/docroot "$@"
