#!/bin/bash

cd $(dirname $0)

. ./.env

TTY=""
if [ "$1" == "-t" ]; then
  TTY=$1; shift
fi

exec docker run --rm -i $TTY \
    --volumes-from "${COMPOSE_PROJECT_NAME}_phpfpm_1" \
    -e "MYSQL_ENV_MYSQL_DATABASE=$MYSQL_DATABASE" \
    -e "MYSQL_ENV_MYSQL_USER=$MYSQL_USER" \
    -e "MYSQL_ENV_MYSQL_PASSWORD=$MYSQL_PASSWORD" \
    -e "MYSQL_ENV_MYSQL_HOST=${COMPOSE_PROJECT_NAME}_db_1" \
    -e "MYSQL_DATABASE" \
    -e "MYSQL_USER" \
    -e "MYSQL_PASSWORD" \
    -e "MYSQL_HOST=${COMPOSE_PROJECT_NAME}_db_1" \
    -e "SOLR_ENV_SOLR_HOST=${COMPOSE_PORJECT_NAME}_solr_1" \
    -e "CMS_DEPLOYMENT" \
    -e "CMS_ENVIRONMENT" \
    gened/drush -r /var/www/html/docroot "$@"
