<?php

/**
 * @file.
 * Module to handle all Glossary related functionality.
 *
 * Provides:
 *  - Exports glosssary taxonomy
 *  - Creates UI and functionality for glossary page.
 *  - Handles Administrative ability to update / delete items from the Glossary.
 */

include_once 'sbac_lexicon.features.inc';

/**
 * Implements hook_update_projects_alter().
 *
 * @param $projects
 */
function sbac_lexicon_update_projects_alter(&$projects) {
  unset($projects['sbac_lexicon']);
}

/**
 * Implements hook_menu_alter().
 */
function sbac_lexicon_menu_alter(&$items) {
  // Get all the id's of vocabularies that are configured in the settings.
  $vids = variable_get('lexicon_vids', array());

  // Create a menu item for each vocabulary with the configured path and title.
  foreach ($vids as $vid) {
    // Don't create menu items for vocabularies that are not Lexicon
    // vocabularies.
    if ($vid != 0) {
      $lexicon_path = variable_get('lexicon_path_' . $vid, 'lexicon/' . $vid);
      $items[$lexicon_path]['page callback'] = 'sbac_lexicon_page';
      unset($items[$lexicon_path]['file']);
    }
  }
}

/**
 * Callback
 */
function sbac_lexicon_page($letter = NULL) {
  module_load_include('inc', 'lexicon', 'lexicon.pages');
  $title = drupal_get_title();
  $output = _lexicon_page($letter);

  if ($letter != NULL) {
    if (drupal_strlen($letter) != 8 || drupal_substr($letter, 0, 7) != 'letter_') {
      return MENU_NOT_FOUND;
    }
    else {
      $letter = drupal_substr($letter, 7, 1);
      drupal_set_title(t('@title: @let', array(
        '@title' => $title,
        '@let' => drupal_strtoupper($letter),
      )));
    }
  }
  return $output;
}

/**
 * Implements hook_theme_registry_alter().
 */
function sbac_lexicon_theme_registry_alter(&$theme_registry) {
//  $theme_registry['lexicon_overview']['template'] = drupal_get_path('theme', 'SBAC') . '/templates/sbac_lexicon/lexicon-overview';
//  $theme_registry['lexicon_overview']['theme path'] = drupal_get_path('module', 'sbac_lexicon');
  $theme_registry['lexicon_overview']['preprocess functions'][] = 'sbac_preprocess_lexicon_overview';
//  $theme_registry['lexicon_alphabar']['template'] = drupal_get_path('theme', 'SBAC') . '/templates/sbac_lexicon/lexicon-alphabar';
//  $theme_registry['lexicon_overview_section']['template'] = drupal_get_path('theme', 'SBAC') . '/templates/sbac_lexicon/lexicon-overview-section';
}
