<?php
/**
 * @file
 * sbac_resource_taxonomy_states.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function sbac_resource_taxonomy_states_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Florida',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0042b7d8-0862-4cfb-944e-32ec9ff59356',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Nevada',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01e4d9f0-48e2-48fd-912e-59e261029c21',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Oregon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '071b1045-b827-4ca3-870f-a81d264d2819',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Alabama',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0bf99376-a52d-45fe-91c4-278abc59af56',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Wisconsin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c9e54aa-230e-478d-a5a8-ffcb33a0ab84',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Michigan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '11b82ac1-e265-41b1-a4ff-d7ae388eadca',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Marshall Islands',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '16abc085-e019-444d-9e93-ee52ea734c24',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Federated States Of Micronesia',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '18b6f46b-866a-4a3d-9b90-c75633d8f3c3',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Tennessee',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1b80408b-b7a7-4fda-9ff7-75ac27944d1a',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Maryland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e606b7c-cc9e-4adb-b2ba-a529456f31ad',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'MO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2303c55f-f728-4d64-9e06-bc0f095d1555',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Hawaii',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '25e39f8e-7133-4e44-9320-842d658777e8',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'North Carolina',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2eecca44-252e-4270-8dbd-8d47a3a75d9d',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Vermont',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '302bb80e-41d4-4f93-96de-cfaa263dff3f',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Northern Mariana Islands',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '314114bd-831d-4c2d-aa39-ac6dceb2059c',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'District Of Columbia',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '32f0c165-f59e-44d9-b7c5-9b08bc86f77e',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Colorado',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4465c817-1a78-4169-aa90-982b7979d04c',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Kansas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '472ab551-526e-401d-ad66-097cb9527ff4',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'West Virginia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '49d7f129-4da4-428d-9f87-80ff75bb45dc',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Connecticut',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4c5fd809-b189-436b-97ca-2a7be17772fe',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Kentucky',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4c60e9ed-6949-4102-a596-d940f3ab050d',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Rhode Island',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '509450af-4130-46b5-823f-31a2850085bb',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Louisiana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '53e8871a-d55f-4049-bdd0-88e8102da1c3',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Guam',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '56183e4e-9de9-4996-a584-924552308346',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Alaska',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d766bab-0a90-4236-85af-dc37d1fdf902',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Minnesota',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e32c0cd-31f3-4e4e-844a-3fa6b73d3b6f',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Puerto Rico',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5f90d2f9-513f-49ad-bc5f-59170c45f4c7',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'New Jersey',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '621f4a6d-d2a8-413e-8ca1-109bb5e96fb8',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Test State',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '6239fa0f-1bf6-4feb-a47a-a157ade84773',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Armed Forces Africa, Canada, Europe And Middle East',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '62a45e18-834f-46c7-a7c2-6d06116d8d0d',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'New York',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '65ea9798-51f1-49d9-86c8-7dd8db24467e',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'South Dakota',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '66af4319-e62a-4781-8388-5c5159a9facb',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'New Hampshire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6fae6d28-090a-4d97-9da3-f64d62a9c44e',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Illinois',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '70c5ea66-8f84-4883-afcb-8d41061535f4',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'American Samoa',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7560919b-e9f4-4ce3-90c5-a7c46834f091',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'California',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ae97834-7387-4dcb-8aca-3d83794d6741',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Pennsylvania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b099c41-12a6-4c78-8530-edd866e64f50',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Georgia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7bb3471b-3823-4d9c-adaa-896decce413d',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Palau',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '878d2414-a935-4ea0-b7bc-1ad4fb537294',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Consortium',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8aa8fbdd-4aee-4629-b06c-b28d4502cdab',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Virgin Islands',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8b44e2ba-8f52-4e52-9026-7099ea470c08',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Indiana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8d7e5447-8d78-4db6-bbd6-e7093d380732',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Montana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9ad66653-64c6-47e9-b01a-82ac44757e05',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Texas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9af205e6-f9a5-46a7-9799-ef6c74ea96e8',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Utah',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9b572e5d-dac5-4204-896e-9328cc8eba10',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Armed Forces Americas',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a34bc3d4-4e24-42cb-ab9c-fbd25ca4723d',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Delaware',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a59ffdb3-93a3-46f8-b9f1-34f0e7dc1027',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Wyoming',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ab4e38b0-e37c-4673-9084-0b820c8daee5',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Oklahoma',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'acaa9431-60ca-4304-bbb7-b408b4629dc9',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'North Dakota',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ae36456b-a3bf-48a9-a4e6-4ae43d1bf827',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Virginia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af06c6a6-99bf-4fe1-ba48-de7a81145487',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Massachusetts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b14914c0-e317-4652-b1a7-6a6f1538068b',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Arkansas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b388c4c0-7c16-4abd-991f-d4ca30174e3a',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Ohio',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b6fc518e-8c13-4140-9149-c9a95d4c685f',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Iowa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bbf591ff-fa86-487f-98b5-20c995c6d55a',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Idaho',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bddf8f83-e113-4a20-aee7-55b1a50a5e49',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Nebraska',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c166a4a8-d706-48a6-92dd-644063370ab4',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'South Carolina',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c2893b3b-b51f-454c-9b07-67228bf453e2',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Washington',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1c9aed5-cbdc-476f-8295-7812e144eb96',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Mississippi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da21e27c-5718-4776-aa67-40768dc58f56',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Armed Forces Pacific',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'dcc1b078-f09e-4958-b880-5eed706a15fe',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'dcc99931-e658-4bef-8628-e3880a5933d1',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Missouri',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dfeaf9e9-61b2-4de5-b19d-8754dd880005',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Smarter Balanced',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e603c94c-4ce2-4c01-9b70-bcd1c8494597',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'New Mexico',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f07cc452-e7ca-41f9-8146-afb9736cf538',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Arizona',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f2fbf2b3-1d28-48c4-b04c-3eb91e0004e8',
    'vocabulary_machine_name' => 'states',
  );
  $terms[] = array(
    'name' => 'Maine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fdc9fd4a-e254-4de3-8da6-82e259aa3b09',
    'vocabulary_machine_name' => 'states',
  );
  return $terms;
}
