<?php
/**
 * @file
 * Code for the SBAC Aqcuia Search feature.
 */

include_once 'sbac_acquia_search.features.inc';

/**
 * Implements hook_apachesolr_environments().
 * Component alter.
 *
 * @param $environments
 */
function sbac_acquia_search_apachesolr_environments_alter(&$environments) {
  if (!isset($_ENV['AH_SITE_ENVIRONMENT'])) {
    if (isset($environments['acquia_search_server_1'])) {
      $environments['acquia_search_server_1']->conf['apachesolr_read_only'] = '1';
    }
  }
}
