<?php

// Hooks and callbacks for integrating with File Entity module for display.
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'sbac_media') . '/includes/sbac_media.formatters.inc';

include_once 'sbac_media.features.inc';

/**
 * Implements hook_ctools_plugin_api().
 */
function sbac_media_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "file_entity" && $api == "file_default_displays") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_menu().
 *
 * @return mixed
 */
function sbac_media_menu() {
  $items = array();

  $items['sbac-media/%ctools_js/internet-confirm'] = array(
    'page callback' => 'sbac_media_internet_confirm',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'title' => 'You are about to embed a Video',
  );

  $items['sbac-media/%ctools_js/delete-media'] = array(
    'page callback' => 'sbac_media_delete_media',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'title' => 'Delete Confirmation',
  );

  return $items;
}

/**
 * Implements hook_media_internet_providers().
 */
function sbac_media_media_internet_providers() {
  $info['MediaInternetSchoolTubeHandler'] = array(
    'title' => t('SchoolTube'),
  );
  $info['MediaInternetTeacherTubeHandler'] = array(
    'title' => t('TeacherTube'),
  );
  $info['MediaInternetSlideShareHandler'] = array(
    'title' => t('SlideShare'),
  );
  $info['MediaInternetYouTubeHandler'] = array(
    'title' => t('YouTube'),
  );
  $info['MediaInternetVimeoHandler'] = array(
    'title' => t('Vimeo'),
  );
  return $info;
}

/**
 * Implements hook_stream_wrappers().
 */
function sbac_media_stream_wrappers() {
  return array(
    'schooltube' => array(
      'name' => t('SchoolTube videos'),
      'class' => 'MediaSchoolTubeStreamWrapper',
      'description' => t('Videos provided by SchoolTube.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
    'teachertube' => array(
      'name' => t('TeacherTube videos'),
      'class' => 'MediaTeacherTubeStreamWrapper',
      'description' => t('Videos provided by TeacherTube.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
    'slideshare' => array(
      'name' => t('SlideShare presentations'),
      'class' => 'MediaSlideShareStreamWrapper',
      'description' => t('Presentations provided by SlideShare.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
    'youtube' => array(
      'name' => t('YouTube videos'),
      'class' => 'MediaYouTubeStreamWrapper',
      'description' => t('Videos provided by YouTube.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
    'vimeo' => array(
      'name' => t('Vimeo videos'),
      'class' => 'MediaVimeoStreamWrapper',
      'description' => t('Presentations provided by Vimeo.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function sbac_media_theme($existing, $type, $theme, $path) {
  return array(
    'media_sbac_schooltube_video' => array(
      'variables' => array('uri' => NULL, 'options' => array()),
      'file' => 'sbac_media.theme.inc',
      'path' => $path . '/includes',
      'template' => 'media-schooltube-video',
    ),
    'media_sbac_teachertube_video' => array(
      'variables' => array('uri' => NULL, 'options' => array()),
      'file' => 'sbac_media.theme.inc',
      'path' => $path . '/includes',
      'template' => 'media-teachertube-video',
    ),
    'media_sbac_schooltube_video' => array(
      'variables' => array('uri' => NULL, 'options' => array()),
      'file' => 'sbac_media.theme.inc',
      'path' => $path . '/includes',
      'template' => 'media-slideshare-presentation',
    ),
  );
}

/**
 * Implements hook_file_mimetype_mapping_alter().
 *
 * Regster the video/youtube mimetype.
 */
function sbac_media_file_mimetype_mapping_alter(&$mapping) {
  $mapping['mimetypes'][] = 'video/schooltube';
  $mapping['mimetypes'][] = 'video/teachertube';
  $mapping['mimetypes'][] = 'video/slideshare';
  $mapping['mimetypes'][] = 'video/youtube';
  $mapping['mimetypes'][] = 'video/vimeo';
}

/*
 * Helper function to create embed URLs because of different implmenetation
 */
function sbac_media_create_embed_url($file) {
  $wrapper = file_stream_wrapper_get_instance_by_uri($file['uri']);
  $parts = $wrapper->get_parameters();
  $id = check_plain($parts['v']);

  switch($file['filemime']) {
    case 'video/schooltube': 
      $url = '//www.schooltube.com/embed_force/' . $id;
      break;
    case 'video/slideshare':
      $url = '//www.slideshare.net/slideshow/embed_code/' . $id . '?rel=0';
      break;
    case 'video/teachertube':
      $url = 'http://www.teachertube.com/embed.php?pg=video_' . $id;
      break;
    case 'video/vimeo':
      $url = '//player.vimeo.com/video/' . $id;
      break;
    case 'video/youtube':
      $url = '//www.youtube.com/embed/' . $id;
      break;
  }
  return url($url, array('external' => TRUE));
}

/**
 * Creates a form file upload element custom to SBAC.
 *
 * @param $form
 */
function sbac_media_widget_form_element(&$form, &$form_state) {
  if (isset($form_state['build_info']['args'][1]) && $form_state['build_info']['args'][1] == 'edit_tags') {
    return;
  }

  $form['#attached']['js'][] = drupal_get_path('module', 'sbac_media') . '/js/sbac_media.form.js';
  $form['#attached']['js'][] = 'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
  $form['#attached']['css'][] = 'http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css';
  $form['#attached']['css'][] = drupal_get_path('module', 'sbac_media') . '/css/sbac_media.css';

  $form['field_file_container']['#tree'] = TRUE;
  $form['field_file_container'] = array(
    '#prefix'=>'<div id="sbac-field-file-container">',
    '#suffix'=>'</div>',
  );

  $media_items = sbac_media_load_items($form['#node']->nid);
  if ($media_items) {
    $output = _sbac_media_create_list($media_items);
    $form['field_file_container']['materials'] = array(
      '#markup' => $output,
    );
  }

  $weight = array();
  if ($media_items) {
    foreach ($media_items as $key => $media_item) {
      if ($media_item['weight']) {
        $weight[$media_item['id']] = $media_item['weight'];
      }
      else {
        $weight[$media_item['id']] = $key;
      }
    }
  }

  $form['field_file_container']['weights'] = array(
    '#type' => 'hidden',
    '#attributes' => array('id' => 'sbac-media-weights'),
    '#value' => drupal_json_encode($weight),
  );

  $form['field_file_container']['field_embed_video'] = array(
    '#type' => 'textfield',
    '#title' => t('Embed Video URL'),
  );

  $form['field_file_container']['field_embed_video_button'] = array(
    '#type' => 'submit',
    '#value' => 'Add Embedded Video',
    '#sbac_embed_video' => TRUE,
    '#validate' => array('sbac_media_widget_form_element_validate'),
    '#ajax'=> array(
      'callback'=>'sbac_media_widget_form_element_upload',
      'wrapper'=> 'sbac-field-file-container',
      'method'=> 'replace',
      'effect'=> 'fade',
    ),
  );

  $form['field_file_container']['field_embed_video_modal'] = array(
    '#markup' => l(t('Modal'), 'sbac-media/nojs/internet-confirm', array(
      'attributes' => array(
        'class' => 'ctools-use-modal button use-ajax ctools-modal-sbac-media-internet-confirm',
        'id' => 'sbac-media-internet-confirm'
      ),
      'query' => array(
        'nid' => $form['#node']->nid,
        'embed' => 'SBAC-MEDIA-EMBEDDED',
      )
    )),
  );

  // JS to properly size the modal.
  $js_settings = array(
    'sbac-media-internet-confirm' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 600,
        'height' => 160,
      ),
    ),
  );
  drupal_add_js($js_settings, 'setting');

  $form['field_file_container']['field_file_upload'] = array(
    '#type' => 'file',
    '#title' => t('Upload2'),
    '#size' => 22,
    '#theme_wrappers' => array(),
  );

  $form['field_file_container']['field_file_upload_button'] = array(
    '#type' => 'submit',
    '#value' => 'upload (25MB Max)',
    '#submit' => array('sbac_media_widget_form_element_upload'),
    '#sbac_embed_video' => FALSE,
    '#ajax'=> array(
      'callback'=>'sbac_media_widget_form_element_upload',
      'wrapper'=> 'sbac-field-file-container',
      'method'=> 'replace',
      'effect'=> 'fade',
    ),
  );

  $form['#after_build'][] = 'sbac_media_after_build_form';
  $form['#group_children']['field_file_container'] = 'group_materials';
}

/**
 * After build function to add the submit handler in.
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function sbac_media_after_build_form($form, $form_state) {
  $form['#submit'][] = 'sbac_media_widget_form_element_submit_handler';
  return $form;
}

/**
 * Submit handler to set the weights;
 *
 * @param $form
 * @param $form_state
 */
function sbac_media_widget_form_element_submit_handler($form, $form_state) {
  if (isset($form_state['input']['weights']) && $form_state['input']['weights']) {
    $weights = drupal_json_decode($form_state['input']['weights']);
    if ($weights) {
      foreach ($weights as $media_id => $weight) {
        db_query("UPDATE {eck_media} SET weight = :weight WHERE id = :id", array(':weight' => $weight, ':id' => $media_id));
      }
    }
  }
}

/**
 * @param $media_items
 * @return string
 */
function _sbac_media_create_list($media_items) {
  $output = '<table id="sbac-media-list" class="sortable">';
  $output .= '<thead><tr><th colspan="3">Machine Name</th><th>Operations</th></tr></thead>';

  foreach ($media_items as $key => $media_item) {
    // Open.
    $output .= '<tr id="' . $media_item['id'] . '">';

    // Image.
    $url = 'public://file.png';
    $image = theme('image_style', array(
      'style_name' => '50x50',
      'path' => $url,
      'attributes' => array('class' => 'awesome-class')
    ));
    $output .= '<td>' . $image . '</td>';

    // Filename.
    $output .= '<td class="ui-icon">' . $media_item['filename'] . '</td>';

    // Filesize.
    $bytes = '0 KB';
    if ($media_item['filesize']) {
      $bytes = number_format($media_item['filesize'] / 1024, 2) . ' KB';
    }
    $output .= '<td>' . $bytes . '</td>';

    // Delete link.
    $delete_link = l(t('Delete'), 'sbac-media/nojs/delete-media', array(
      'attributes' => array(
        'class' => 'ctools-use-modal use-ajax ctools-modal-sbac-media-modal-delete-media',
        'id' => 'sbac-media-modal-delete-media'
      ),
      'query' => array(
        'fid' => $media_item['fid'],
        'nid' => $media_item['nid'],
        'id' => $media_item['id'],
      )
    ));
    $output .= '<td>' . $delete_link . '</td>';

    // Close.
    $output .= '</tr>';
  }
  $output .= '</table>';

  // JS to properly size the modal.
  $js_settings = array(
    'sbac-media-modal-delete-media' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 600,
        'height' => 160,
      ),
    ),
  );
  drupal_add_js($js_settings, 'setting');

  return $output;
}

/**
 * Validate embedded videos.
 *
 * @param $form
 * @param $form_state
 */
function sbac_media_widget_form_element_validate($form, $form_state) {
  if ($form_state['values']['field_embed_video']) {
    $embed_video = strtolower($form_state['values']['field_embed_video']);
    if (strpos($embed_video, 'youtube') === FALSE && strpos($embed_video, 'teachertube') === FALSE && strpos($embed_video, 'schooltube') === FALSE && strpos($embed_video, 'vimeo') === FALSE && strpos($embed_video, 'slideshare') === FALSE) {
      form_set_error('field_embed_video', t('The following URL: ' . $form_state['values']['field_embed_video'] . ' cannot be embedded. Only videos from the following accepted hosts are allowed: YouTube, Vimeo, SchoolTube, TeacherTube and SlideShare.'));
    }
  }
  else {
    form_set_error('field_embed_video', t('You must add at least one material.'));
  }
}

/**
 * The form element submit handler.
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function sbac_media_widget_form_element_upload($form, $form_state) {
  if (form_get_errors()) {
    return $form['field_file_container'];
  }

  if ($form_state['clicked_button']['#sbac_embed_video']) {
    $embedded_video_source = $form_state['values']['field_embed_video'];
    if (strpos($embedded_video_source, 'youtube') !== FALSE || strpos($embedded_video_source, 'vimeo') !== FALSE) {
       $_SESSION['field_embed_video'] = $embedded_video_source;
      $form['field_file_container']['run_js'] = array(
        '#markup' => '<script>jQuery("#sbac-media-internet-confirm").click();</script>',
      );
    }
    else {
      if (isset($form_state['node'])) {
        $node = $form_state['node'];
        sbac_media_save_embedded_source($embedded_video_source, $node->nid);
      }
    }
  }
  else {
    $allowed_file_types = array('txt doc docx pdf xls xlsx pptx ppt odt odp mp4 mov mp3 aac png jpg jpeg mpg avi ods');
    $file = file_save_upload('field_file_upload', array('file_validate_extensions' => $allowed_file_types), "private://", $replace = FILE_EXISTS_REPLACE);
    if ($file && !$form_state['executed']) {
      if (isset($form_state['node'])) {
        $node = $form_state['node'];

        // Create the media item, duplicates get checked later.
        $media = new stdClass;
        $media->type = 'media';
        $media->fid = $file->fid;
        $media->nid = $node->nid;
        $media->filename = $file->filename;
        $media->file_size = $file->filesize;
        entity_save('media', $media);
      }
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);
    }
  }

  // Update the view
  $media_items = sbac_media_load_items($form['#node']->nid);
  if ($media_items) {
    $output = _sbac_media_create_list($media_items);
    $form['field_file_container']['materials']['#markup'] = $output;
    $form['field_file_container']['materials']['#weight'] = 10;
  }

  return $form['field_file_container'];
}

/**
 * @param $nid
 * @return array
 */
function sbac_media_load_items($nid) {
  $media_items = array();
  if ($nid) {
    $result = db_query("SELECT * FROM {eck_media} WHERE nid = :nid ORDER BY weight", array(':nid' => $nid));
    foreach ($result as $row) {
      $media_item = array();
      $media_item['id'] = $row->id;
      $media_item['fid'] = $row->file_id;
      $media_item['nid'] = $row->nid;
      $media_item['filename'] = $row->filename;
      $media_item['filesize'] = $row->file_size;
      $media_item['filehash'] = $row->file_hash;
      $media_item['weight'] = $row->weight;
      $media_items[] = $media_item;
    }
  }
  return $media_items;
}

/**
 * Deletes the media record.
 *
 * @param $id
 * @param null $fid
 */
function sbac_media_delete_media_record($id, $fid = NULL) {
  if ($id) {
    db_query('DELETE FROM {eck_media} WHERE id = :id', array(':id' => $id));
  }

  if ($fid) {
    // @TODO
  }
}

/**
 * Displays the media delete modal.
 *
 * @param bool $js
 */
function sbac_media_delete_media($js = FALSE) {
  if ($js) {
    ctools_include('ajax');
    ctools_include('modal');
    ctools_add_js('ajax-responder');
    ctools_modal_add_js();

    $form_state = array(
      'title' => t('To continue, confirm that you wish to delete this media.'),
      'ajax' => $js,
    );

    $output = ctools_modal_form_wrapper('sbac_media_delete_media_form', $form_state);

    // This means the form has been executed.
    if (!empty($form_state['executed'])) {
      $output = array();
      $output[] = ctools_modal_command_dismiss();
      if ($form_state['triggering_element']['#value'] != 'Cancel') {
        // Delete document reference.
        if ($form_state['values']['id']) {
          sbac_media_delete_media_record($form_state['values']['id'], $form_state['values']['fid']);
        }
        $output[] = ctools_ajax_command_redirect($form_state['values']['hidden_url'], 0, array('fragment' => 'edit-group_materials'));
        $output[] = ctools_ajax_command_reload();
      }
    }
    print ajax_render($output);
    exit();
  }
  else {
    return;
  }
}

/**
 * The cancel / delete form
 *
 * @return array
 */
function sbac_media_delete_media_form() {
  $form = array();

  $form['hidden_url'] = array(
    '#type' => 'hidden',
    '#value' => $_SERVER['HTTP_REFERER'],
  );

  $form['fid'] = array(
    '#type' => 'hidden',
    '#value' => $_GET['fid'],
  );

  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $_GET['nid'],
  );

  $form['id'] = array(
    '#type' => 'hidden',
    '#value' => $_GET['id'],
  );

  $form['submit_description'] = array(
    '#markup' => '<p>' . t('If you wish to continue, click delete!') . '</p>',
  );

  $form['cancel'] = array(
    '#type' => 'submit',
    '#value' => 'Cancel',
    '#attributes' => array('id' => array('edit-cancel-media-overlay'))
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Delete',
    '#attributes' => array('id' => array('edit-delete-media-overlay'))
  );

  return $form;
}

/**
 * Displays the media delete modal.
 *
 * @param bool $js
 */
function sbac_media_internet_confirm($js = FALSE) {
  if ($js) {
    ctools_include('ajax');
    ctools_include('modal');
    ctools_add_js('ajax-responder');
    ctools_modal_add_js();

    $form_state = array(
      'title' => t('You are about to embed a Video'),
      'ajax' => $js,
    );

    $output = ctools_modal_form_wrapper('sbac_media_internet_confirm_form', $form_state);

    // This means the form has been executed.
    if (!empty($form_state['executed'])) {
      $output = array();
      $output[] = ctools_modal_command_dismiss();
      if ($form_state['triggering_element']['#value'] != 'Cancel') {
        sbac_media_save_embedded_source($form_state['values']['embed'], $form_state['values']['nid']);
        $output[] = ctools_ajax_command_redirect($form_state['values']['hidden_url'], 0, array('fragment' => 'edit-group_materials'));
        $output[] = ctools_ajax_command_reload();
      }
    }
    print ajax_render($output);
    exit();
  }
  else {
    return;
  }
}

/**
 * The cancel / delete form
 *
 * @return array
 */
function sbac_media_internet_confirm_form() {
  $form = array();

  $form['hidden_url'] = array(
    '#type' => 'hidden',
    '#value' => $_SERVER['HTTP_REFERER'],
  );

  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $_GET['nid'],
  );

  $form['embed'] = array(
    '#type' => 'hidden',
    '#value' => $_SESSION['field_embed_video'],
  );

  $form['description'] = array(
    '#markup' => '<p>' . t('There are oftentimes issues with the playback of YouTube / Vimeo videos on filtered networks.') . '</p>',
  );

  $form['submit_description'] = array(
    '#markup' => '<p>' . t('Are you sure you want to continue?') . '</p>',
  );

  $form['cancel'] = array(
    '#type' => 'submit',
    '#value' => 'Cancel',
    '#attributes' => array('id' => array('edit-cancel-media-embed'))
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Embed Video',
    '#attributes' => array('id' => array('edit-delete-media-embed'))
  );

  return $form;
}

/**
 * API call to retrieve title and save media.
 *
 * @param $embedded_video_source
 */
function sbac_media_save_embedded_source($embedded_video_source, $nid) {
  if ($embedded_video_source == NULL || $nid == NULL) {
    return;
  }

  // API Call to retrieve Titles. (Would like to get length but no API provides it)
  if (strpos($embedded_video_source, 'schooltube') !== FALSE) {
    $handler = new MediaInternetSchoolTubeHandler($embedded_video_source);
    $file = $handler->getFileObject();
  }

  if (strpos($embedded_video_source, 'teachertube') !== FALSE) {
    $handler = new MediaInternetTeacherTubeHandler($embedded_video_source);
    $file = $handler->getFileObject();
  }

  if (strpos($embedded_video_source, 'slideshare') !== FALSE) {
    $handler = new MediaInternetSlideShareHandler($embedded_video_source);
    $file = $handler->getFileObject();
  }

  if (strpos($embedded_video_source, 'youtube') !== FALSE) {
    $handler = new MediaInternetYouTubeHandler($embedded_video_source);
    $file = $handler->getFileObject();
  }

  if (strpos($embedded_video_source, 'vimeo') !== FALSE) {
    $handler = new MediaInternetVimeoHandler($embedded_video_source);
    $file = $handler->getFileObject();
  }

  if ($file && isset($file->filename) && $file->filename != NULL) {
    $media = new stdClass;
    $media->type = 'media';
    $media->fid = 0;
    $media->nid = $nid;
    $media->filename = $file->filename;
    $media->file_size = 0;
    $media->weight = 100;
    entity_save('media', $media);
  }
}
