<?php
/**
 * Implements of hook_update_N().
 *
 * Delete the alignment_type vocabulary
 */
function sbac_alignment_update_7001() {
  $ret = array();

  module_load_include('taxonomy','inc','field','field.crud','field_sql_storage');

  $findme = "alignment_type";
  $vocs = taxonomy_vocabulary_get_names();
  if (isset($vocs[$findme])) {
     $vid = $vocs[$findme]->vid;
     taxonomy_vocabulary_delete($vid);
     return true;
  }

  return false;
}
/**
 * Implements hook_update_N().
 * 
 * Delete and rebuild the alignment_type and education_alignment vocab
 */
function sbac_alignment_update_7002() {
  //
}
/**
 * Implements hook_update_N().
 * 
 * Delete and rebuild the alignment_type and education_alignment vocab
 */
function sbac_alignment_update_7003() {
  $alignment_type_vocab_name = 'alignment_type';
  $edu_alignment_vocab_name = "education_alignment";
  
  $alignment_type_vocab = taxonomy_vocabulary_machine_name_load($alignment_type_vocab_name);
  $edu_alignment_vocab = taxonomy_vocabulary_machine_name_load($edu_alignment_vocab_name);
  $vocab_array = array($alignment_type_vocab, $edu_alignment_vocab);
  
  //Remove all existing terms
  foreach ($vocab_array as $vocab) {
    $terms = taxonomy_get_tree($vocab->vid);
    
    foreach ($terms as $term) {
      taxonomy_term_delete($term->tid);
    }
  }
  
  // Add alignment type
  $terms = array(
    'Assesses' => array(
      'desc' => 'lorem ipsum',  
    ),
    'Teaches' => array(
      'desc' => 'lorem ipsum',  
    ),
    'Requires' => array(
      'desc' => 'lorem ipsum',  
    ),
  );
  sbac_alignment_add_terms($alignment_type_vocab->vid, $terms);
  
  // Add education alignment
  $terms = array(
    'English Language Arts' => array(
      'desc' => 'lorem ipsum',
      'children' => array(
        '1IT' =>  array(
          'desc' => 'lorem ipsum',
          'children' => array(
            '10-1' =>  array(
              'desc' => 'lorem ipsum',
              'children' => array(
                '10.L.4a' => array(
                  'desc' => 'lorem ipsum',
                ),
                '10.L.4b' => array(
                  'desc' => 'lorem ipsum',
                ),
                '10.L.4c' => array(
                  'desc' => 'lorem ipsum',
                ),
              ),
            ),
          ),
        ),
        '1LT' =>  array(
          'desc' => 'lorem ipsum',
          'children' => array(
            '11-1' =>  array(
              'desc' => 'lorem ipsum',
              'children' => array(
                '11.L.4a' => array(
                  'desc' => 'lorem ipsum',
                ),
                '11.L.4b' => array(
                  'desc' => 'lorem ipsum',
                ),
                '11.L.4c' => array(
                  'desc' => 'lorem ipsum',
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  );
  sbac_alignment_add_terms($edu_alignment_vocab->vid, $terms);
  
  return ;
}
/**
 * Implements hook_update_N().
 * Install sample set for ELA terms
 */
function sbac_alignment_update_7004() {
  //Deleted implementation
}
/**
 * Implements hook_update_N().
 * Deleting dot notation and item url field.
 */
function sbac_alignment_update_7005() {
  $field = field_info_instance('node', 'field_dot_notation', 'alignment');
  field_delete_instance($field);
  
  $field = field_info_instance('node', 'field_item_url', 'alignment');
  field_delete_instance($field);
}
/**
 * Implements hook_update_N().
 * Instantiating the variables
 */
function sbac_alignment_update_7006() {
  variable_set('sbac_alignment_import_counter', 0);
  variable_set('sbac_alignment_import_data', array());
  variable_set('sbac_alignment_import_bad_terms', array());
}