<?php

/*
 * Environment specific Site Settings.
 * 
 * $databases['default']['default'] = array(
 *   'driver' => '',
 *   'database' => '',
 *   'username' => '',
 *   'password' => '',
 *   'host' => '',
 *   'collation' => '',
 * );
 * 
 * $conf['file_private_path'] = '';
 */

/**
 * Google OSCaddie Environment Sepecific Settings.
 * 
 * $conf['google_cdn_folder'] = 'local';
 * $conf['oscaddie_gcs_folder'] = 'local';
 */

/**
 * SBAC SSO Settings
 * 
 * define('SBAC_SSO_URL', '');
 * define('SBAC_SSO_PROGRAM_REQUEST_AUTH', '');
 * define('SBAC_SSO_PROGRAM_OAUTH_API_LIST', '');
 * define('SBAC_SSO_PROGRAM_OAUTH_API', '');
 * define('SBAC_SSO_DESTROY_SESSION_URL', '');
 * define('SBAC_SSO_LOGOUT_REDIRECT_URL', '');
 * 
 */

/**
 * SBAC Search Settings
 * 
 * 
 * $conf['sbac_search_env_env_id'] = '';
 * $conf['sbac_search_env_name'] = '';
 * $conf['sbac_search_env_url'] = '';
 * $conf['sbac_search_env_service_class'] = '';
 * $conf['sbac_search_env_conf'] = array(
 *   'acquia_override_auto_switch' => 1,
 *   'acquia_override_selector' => '',
 *   'acquia_override_subscription_corename' => '',
 *   'acquia_override_subscription_id' => '',
 *   'acquia_override_subscription_key' => '',
 *   'acquia_search_key' => '',
 *   'apachesolr_access_always_add_grants' => 0,
 *   'apachesolr_direct_commit' => 0,
 *   'apachesolr_read_only' => '1',
 *   'apachesolr_soft_commit' => 0,
 *  );
 * 
 * 
 */