<?php
/**
 * @file
 * Code for the SBAC Export CSV feature.
 */

include_once 'sbac_export_csv.features.inc';


/**
 * Implements hook_menu_alter().
 */
function sbac_export_csv_menu_alter(&$items) {
  $item = array(
    'title' => t('Exports'),
    'weight' => 100,
    'access callback' => TRUE,
    'page callback' => 'drupal_goto',
    'page arguments' => array('exports'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/sbac/exports'] = $item;

}