<?php

/**
 * @file
 * Module file for adding a "More Comments" button in the comment pagination.
 */

/**
 * Implements of hook_menu().
 */
function morecomments_menu() {
  $items['morecomments'] = array(
    'title' => 'More comments',
    'page callback' => 'morecomments_comment_render',
    'access arguments' => array('access comments'),
    'file' => 'morecomments.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function morecomments_permission() {
  return array(
    'administer morecomments' => array(
      'title' => t('Administer morecomments'),
      'description' => t('Perform administration tasks for morecomments module.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function morecomments_form_node_type_form_alter(&$form, $form_state) {
  // Add more options to the comments per page settings
  $form['comment']['comment_default_per_page']['#options'] = drupal_map_assoc(array(5, 10, 15, 30, 50, 70, 90, 150, 200, 250, 300));

  $form['comment']['morecomments_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable morecomments pager for the node type'),
    '#default_value' => variable_get('morecomments_enabled_' . $form['#node_type']->type, 0),
    '#access' => user_access('administer morecomments'),
  );
  $form['comment']['morecomments_text'] = array(
    '#type' => 'textfield',
    '#title' => t('More comments text for the pager'),
    '#default_value' => variable_get('morecomments_text_' . $form['#node_type']->type, t('More comments')),
    '#access' => user_access('administer morecomments'),
  );
}

/**
 * Implements of hook_theme().
 */
function morecomments_theme($existing, $type, $theme, $path) {
  return array(
    'morecomments_pager' => array(
      'variables' => array(
        'nid' => NULL,
        'next_page' => NULL,
        'node_type' => NULL,
      ),
    ),
  );
}

/**
 * Theme function that renders the pager.
 */
function theme_morecomments_pager($variables) {
  return "<a href = 'javascript:;' class='morecomments-button node-" . $variables['nid'] . " page-" . $variables['next_page'] . "'>" . check_plain(variable_get('morecomments_text_' . $variables['node_type'], t('More comments'))) . "</a>";
}

/**
 * Implements of hook_node_view().
 */
function morecomments_node_view($node, $view_mode, $langcode) {
  if ($node->comment && $view_mode == 'full' && node_is_page($node) && empty($node->in_preview) &&  variable_get('morecomments_enabled_' . $node->type, 0)) {
    drupal_add_js(array('morecomments_pager' => theme('morecomments_pager', array('nid' => $node->nid, 'next_page' => 1, 'node_type' => $node->type))), 'setting');
    drupal_add_js(drupal_get_path('module', 'morecomments') . '/morecomments.js', 'file');
    drupal_add_css(drupal_get_path('module', 'morecomments') . '/morecomments.css');
  }
}
